import type { PayLocale } from '../types';

export interface PayTrainingTopic {
  id: string;
  title: string;
  summary: string;
  steps: readonly string[];
  note: string;
}

type TrainingMessages = {
  title: string;
  subtitle: string;
  readBeforeTicket: string;
  topicCount: (count: number) => string;
  topics: readonly PayTrainingTopic[];
};

const topics = {
  'fa-IR': [
    { id:'onboarding', title:'شروع کار و راه‌اندازی Merchant', summary:'برای دریافت پرداخت ابتدا باید حساب فعال، Merchant و کیف پول دریافت معتبر داشته باشید.', steps:['از بخش «Merchant و کیف پول دریافت» اطلاعات کسب‌وکار را بررسی یا Merchant را ایجاد کنید.','یک کیف پول دریافت را متصل یا کیف پول اختصاصی SolMint را ایجاد کنید و عبارت بازیابی را امن نگه دارید.','مالکیت کیف پول را با challenge سرور تأیید کنید؛ فقط وضعیت تأییدشده برای دریافت پرداخت معتبر است.'], note:'SolMint عبارت بازیابی یا کلید خصوصی را روی سرور ذخیره نمی‌کند. وضعیت Merchant و کیف پول از سرویس رسمی خوانده می‌شود.' },
    { id:'account-wallet', title:'حساب کاربری و کیف پول', summary:'با کلیک روی بخش نام و کیف پول در هدر، اطلاعات حساب و موجودی کیف پول دریافت را می‌بینید.', steps:['موجودی SOL، USDT و USDC از شبکه Solana از طریق سرویس Pay خوانده می‌شود.','آدرس کیف پول دریافت و زمان آخرین مشاهده را بررسی کنید؛ موجودی ممکن است به‌دلیل وضعیت شبکه کمی قدیمی باشد.','برای پایان نشست از گزینه «خروج از حساب» استفاده کنید.'], note:'موجودی نمایشی یک snapshot شبکه است و به‌تنهایی وضعیت حسابداری Merchant یا تسویه مالی را تعیین نمی‌کند.' },
    { id:'overview', title:'نمای کلی و Dashboard', summary:'Dashboard برای مشاهده سریع وضعیت Merchant و داده‌های عملیاتی پرداخت طراحی شده است.', steps:['وضعیت Merchant و آماده‌بودن کیف پول را در بالای صفحه بررسی کنید.','شاخص‌های مالی و عملیاتی را فقط از داده‌های authoritative سرویس Pay دنبال کنید.','برای بررسی جزئیات، از مسیر مربوط به Transactions، Invoices، Payment Links یا Reports وارد شوید.'], note:'اعداد مالی در Frontend محاسبه authoritative نمی‌شوند؛ منبع حقیقت Backend و Database است.' },
    { id:'checkout', title:'پرداخت و Checkout', summary:'Checkout محل نمایش Payment Intent و اجرای تجربه پرداخت مشتری است.', steps:['Payment Intent معتبر را باز کنید و مبلغ، Asset، مقصد، کارمزد و انقضا را بررسی کنید.','تراکنش را از طریق کیف پول مشتری ارسال کنید؛ ارسال تراکنش هنوز به معنی موفقیت پرداخت نیست.','منتظر وضعیت Verification و نتیجه authoritative Backend بمانید و فقط همان وضعیت را ملاک قرار دهید.'], note:'زنجیره وضعیت پرداخت باید بین submitted، detected، verifying و confirmed/completed تفاوت بگذارد.' },
    { id:'transactions', title:'Transactions', summary:'Transactions مرکز عملیاتی برای جست‌وجو و بررسی پرداخت‌هاست.', steps:['پرداخت را بر اساس Payment ID، Signature، Customer یا Status پیدا کنید.','Amount، Asset، Fee، Settlement و زمان‌های ثبت/تأیید را بررسی کنید.','برای خطاهایی مثل underpaid، overpaid، wrong token، wrong recipient یا ambiguous از وضعیت authoritative استفاده کنید.'], note:'Signature یا reference به‌تنهایی proof of payment نیست.' },
    { id:'customers', title:'Customers', summary:'Customers برای مشاهده اطلاعات مشتریان مرتبط با پرداخت‌های Merchant استفاده می‌شود.', steps:['رکورد مشتری را از داده‌های ثبت‌شده سرویس Pay مشاهده کنید.','برای ارتباط با یک پرداخت، Payment ID یا داده‌های transaction مربوط را بررسی کنید.','در صورت بروز اختلاف، از داده‌های authoritative Backend و نه داده‌های محلی استفاده کنید.'], note:'اطلاعات مشتری فقط در محدوده دسترسی Merchant مجاز باید دیده شود.' },
    { id:'billing-links', title:'Invoices و Payment Links', summary:'در بخش صورتحساب، Invoice و لینک پرداخت ثابت را می‌سازید و مدیریت می‌کنید.', steps:['برای Invoice، مبلغ، Asset، توضیح و زمان انقضا را طبق فرم موجود ثبت کنید.','برای Payment Link، slug، عنوان، مبلغ ثابت، Asset، fee payer و زبان Checkout را تنظیم کنید.','لینک عمومی را می‌توانید در تلگرام، پیام‌رسان یا وبسایت خود منتشر کنید؛ مشتری برای پرداخت از SolMint نیاز به ثبت‌نام ندارد.'], note:'در Public Payment Link مشتری نام، نام خانوادگی و علت پرداخت را وارد می‌کند و این اطلاعات همراه Payment Intent در Backend ثبت می‌شود.' },
    { id:'referrals', title:'Referrals و همکاری', summary:'این بخش برای داده‌های همکاری و Referral طراحی شده است.', steps:['کد معرفی و Merchantهای ارجاع‌شده را بررسی کنید.','وضعیت earnings و eligibility را فقط از پاسخ Backend بخوانید.','برای برداشت یا تسویه، فقط شرایط و وضعیت authoritative سرویس را ملاک قرار دهید.'], note:'Frontend نباید commission یا withdrawal eligibility را خودش محاسبه کند.' },
    { id:'reports', title:'Reports', summary:'Reports برای تحلیل حجم و وضعیت پرداخت‌ها در بازه زمانی مختلف است.', steps:['بازه زمانی مورد نظر را انتخاب کنید و timestamp/timezone داده را در نظر بگیرید.','Volume، transaction count، success/failure و settlement را کنار هم بررسی کنید.','برای تصمیم‌های مالی، داده‌های ثبت‌شده Backend را مرجع قرار دهید.'], note:'نمودار ابزار تحلیل است، نه منبع مستقل حقیقت مالی.' },
    { id:'developer', title:'Developer، API Keys و Webhooks', summary:'Developer برای اتصال سرویس‌های فنی Merchant به SolMint Pay است.', steps:['API Key را فقط در محیط امن و مطابق scope آن استفاده کنید.','برای Webhook endpoint و delivery history از بخش Developer استفاده کنید.','Webhook را notification بدانید، نه source of truth مالی؛ وضعیت پرداخت از Verification و Backend می‌آید.'], note:'API secret و Webhook secret نباید در URL، log، frontend storage یا telemetry قرار گیرند.' },
    { id:'security', title:'Security', summary:'Security محل بررسی وضعیت‌های امنیتی، احراز کیف پول و مرزهای دسترسی Pay است.', steps:['وضعیت Wallet Verification و Merchant access را بررسی کنید.','برای خطاهای امنیتی یا دسترسی غیرمجاز از مسیر رسمی Support استفاده کنید.','هرگز seed phrase، private key، API secret یا webhook secret را در Ticket یا مرورگر ثبت نکنید.'], note:'امنیت واقعی در Backend، Authentication، Authorization و RLS enforce می‌شود؛ UI فقط لایه نمایش است.' },
    { id:'tickets', title:'Tickets و پشتیبانی', summary:'قبل از ثبت Ticket، آموزش همین صفحه را مرور کنید؛ بسیاری از خطاهای عملیاتی با بررسی status و Payment Intent قابل تشخیص‌اند.', steps:['موضوع و شرح خطا را دقیق و بدون secret وارد کنید.','در صورت ارتباط، Payment ID، Invoice ID، Ticket ID یا Transaction Signature را در متن تیکت ذکر کنید.','بعد از ثبت، تیکت را از فهرست پایین پیگیری و به پاسخ تیم پشتیبانی پاسخ دهید.'], note:'مرکز آموزش جایگزین تیکت نیست؛ فرم ارسال و پیگیری تیکت در پایین همین صفحه فعال باقی می‌ماند.' },
  ],
  'en-US': [
    { id:'onboarding', title:'Getting started and Merchant setup', summary:'To receive payments, you need an active account, a Merchant, and a valid receiving wallet.', steps:['Open Merchant & receiving wallet and create or review your business profile.','Connect an existing wallet or create a SolMint dedicated wallet and store its recovery phrase securely.','Complete the server wallet challenge flow; only a verified wallet is eligible to receive payments.'], note:'SolMint does not store the recovery phrase or private key on the server. Merchant and wallet state come from the official service.' },
    { id:'account-wallet', title:'Account and wallet', summary:'Click the name and wallet area in the header to view account details and the receiving-wallet balance.', steps:['The SOL, USDT, and USDC balances are read from the Solana network through the Pay service.','Review the receiving address and observation time; network data can become slightly stale.','Use Sign out to end the current authenticated session.'], note:'The displayed balance is a network snapshot; it does not independently determine Merchant accounting or settlement.' },
    { id:'overview', title:'Overview and Dashboard', summary:'Dashboard provides a quick view of Merchant readiness and operational payment data.', steps:['Check Merchant status and receiving-wallet readiness first.','Use authoritative Pay service data for operational and financial indicators.','Open Transactions, Invoices, Payment Links, or Reports for detail.'], note:'The frontend does not calculate authoritative financial truth; the Backend and Database are the source of truth.' },
    { id:'checkout', title:'Payment and Checkout', summary:'Checkout renders the Payment Intent and provides the customer payment experience.', steps:['Open a valid Payment Intent and review amount, asset, destination, fees, and expiration.','Send the transaction through the customer wallet; submission alone is not payment success.','Wait for authoritative verification and follow the backend payment state.'], note:'Submitted, detected, verifying, confirmed, and completed are distinct payment states.' },
    { id:'transactions', title:'Transactions', summary:'Transactions is the operational area for finding and reviewing payments.', steps:['Search by Payment ID, signature, customer, or status.','Review amount, asset, fee, settlement, and timestamps.','For underpaid, overpaid, wrong token, wrong destination, or ambiguous cases, trust the authoritative state.'], note:'A signature or reference by itself is not proof of payment.' },
    { id:'customers', title:'Customers', summary:'Customers contains customer records associated with Merchant payments.', steps:['Review customer information returned by the Pay service.','Use the related Payment ID or transaction data to correlate a customer with a payment.','Resolve disputes from authoritative backend data, not local UI state.'], note:'Customer information must remain within the Merchant authorization boundary.' },
    { id:'billing-links', title:'Invoices and Payment Links', summary:'Billing is where fixed invoices and reusable payment links are created and managed.', steps:['For an Invoice, enter the amount, asset, description, and expiration supported by the form.','For a Payment Link, configure slug, title, fixed amount, asset, fee payer, and Checkout language.','A public link can be shared in Telegram, messaging apps, or a website; the customer does not need a SolMint account to pay.'], note:'Public Checkout collects payer first name, last name, and payment reason and stores them with the Payment Intent server-side.' },
    { id:'referrals', title:'Referrals and partnerships', summary:'This area contains referral and partnership data.', steps:['Review referral codes and referred Merchants.','Use backend-provided earnings and eligibility states.','For withdrawals or payouts, follow only the authoritative service status and rules.'], note:'The frontend must not calculate commission or withdrawal eligibility itself.' },
    { id:'reports', title:'Reports', summary:'Reports helps analyze payment volume and states across time ranges.', steps:['Choose a time range and pay attention to timestamps and timezone.','Review volume, transaction count, success/failure, and settlement together.','Use recorded backend data for financial decisions.'], note:'Charts are an analysis surface, not an independent financial source of truth.' },
    { id:'developer', title:'Developer, API Keys, and Webhooks', summary:'Developer is the technical integration area for Merchant systems.', steps:['Use API Keys only in secure environments and according to their scopes.','Manage Webhook endpoints and delivery history from Developer.','Treat Webhooks as notifications, not as financial truth; payment status comes from verification and the backend.'], note:'API secrets and Webhook secrets must not be placed in URLs, logs, frontend storage, or telemetry.' },
    { id:'security', title:'Security', summary:'Security covers access boundaries, wallet verification, and important security controls.', steps:['Review Wallet Verification and Merchant access state.','Use Support for security incidents or denied access.','Never place a seed phrase, private key, API secret, or webhook secret in a ticket or browser storage.'], note:'Real enforcement is in Backend authentication, authorization, and RLS; the UI is only the presentation layer.' },
    { id:'tickets', title:'Tickets and Support', summary:'Read this training center before opening a ticket; many operational issues can be identified by checking status and Payment Intent details.', steps:['Describe the problem clearly and never include secrets.','When relevant, include Payment ID, Invoice ID, Ticket ID, or transaction signature.','After creation, track the ticket in the list below and reply in the conversation thread.'], note:'The training center does not replace support; ticket creation and ticket history remain active below.' },
  ],
  ar: [
    { id:'onboarding', title:'البدء وإعداد التاجر', summary:'لاستقبال المدفوعات تحتاج إلى حساب فعال وتاجر ومحفظة استلام موثقة.', steps:['افتح قسم التاجر ومحفظة الاستلام وأنشئ بيانات النشاط أو راجعها.','اربط محفظة موجودة أو أنشئ محفظة SolMint مخصصة واحفظ عبارة الاسترداد بأمان.','أكمل تحدي المحفظة على الخادم؛ المحفظة الموثقة فقط صالحة لاستقبال المدفوعات.'], note:'لا تخزن SolMint عبارة الاسترداد أو المفتاح الخاص على الخادم. حالة التاجر والمحفظة تأتي من الخدمة الرسمية.' },
    { id:'account-wallet', title:'الحساب والمحفظة', summary:'اضغط على منطقة الاسم والمحفظة في الرأس لرؤية الحساب ورصيد محفظة الاستلام.', steps:['يتم جلب أرصدة SOL وUSDT وUSDC من شبكة Solana عبر خدمة Pay.','راجع عنوان المحفظة ووقت آخر قراءة؛ قد تصبح بيانات الشبكة قديمة قليلًا.','استخدم تسجيل الخروج لإنهاء الجلسة الحالية.'], note:'الرصيد المعروض لقطة من الشبكة ولا يحدد منفردًا محاسبة التاجر أو التسوية.' },
    { id:'overview', title:'النظرة العامة ولوحة التحكم', summary:'لوحة التحكم تعرض جاهزية التاجر والبيانات التشغيلية بسرعة.', steps:['راجع حالة التاجر وجاهزية محفظة الاستلام.','اعتمد على بيانات خدمة Pay الموثوقة للمؤشرات التشغيلية والمالية.','استخدم المعاملات والفواتير وروابط الدفع والتقارير للتفاصيل.'], note:'لا يحسب الواجهة الحقيقة المالية المعتمدة؛ المصدر هو الخادم وقاعدة البيانات.' },
    { id:'checkout', title:'الدفع وCheckout', summary:'يعرض Checkout الـ Payment Intent ويوفر تجربة الدفع للعميل.', steps:['افتح Payment Intent صالحًا وراجع المبلغ والأصل والوجهة والرسوم والانتهاء.','أرسل المعاملة من محفظة العميل؛ إرسالها وحده لا يعني نجاح الدفع.','انتظر التحقق المعتمد واتبع حالة الدفع التي يعيدها الخادم.'], note:'الإرسال والكشف والتحقق والتأكيد والإكمال حالات مختلفة.' },
    { id:'transactions', title:'المعاملات', summary:'المعاملات هي المركز التشغيلي للبحث في المدفوعات ومراجعتها.', steps:['ابحث باستخدام Payment ID أو التوقيع أو العميل أو الحالة.','راجع المبلغ والأصل والرسوم والتسوية والأوقات.','في حالات underpaid أو overpaid أو الأصل الخاطئ أو الوجهة الخاطئة أو الغموض اعتمد الحالة المعتمدة.'], note:'التوقيع أو المرجع وحده ليس إثباتًا للدفع.' },
    { id:'customers', title:'العملاء', summary:'يعرض هذا القسم سجلات العملاء المرتبطة بمدفوعات التاجر.', steps:['راجع بيانات العميل التي تعيدها خدمة Pay.','اربط العميل بالدفع من خلال Payment ID أو بيانات المعاملة.','حل النزاعات اعتمادًا على بيانات الخادم وليس حالة الواجهة المحلية.'], note:'يجب أن تبقى بيانات العملاء ضمن حدود صلاحية التاجر.' },
    { id:'billing-links', title:'الفواتير وروابط الدفع', summary:'تتم هنا إدارة الفواتير الثابتة وروابط الدفع القابلة لإعادة الاستخدام.', steps:['للفواتير أدخل المبلغ والأصل والوصف والانتهاء بحسب النموذج.','لرابط الدفع اضبط المعرّف والعنوان والمبلغ الثابت والأصل ودافع الرسوم ولغة Checkout.','يمكن مشاركة الرابط العام في Telegram أو تطبيقات المراسلة أو الموقع، ولا يحتاج العميل إلى حساب SolMint للدفع.'], note:'يجمع Checkout العام الاسم الأول واسم العائلة وسبب الدفع ويحفظها مع Payment Intent على الخادم.' },
    { id:'referrals', title:'الإحالات والشراكات', summary:'يحتوي هذا القسم على بيانات الإحالات والشراكات.', steps:['راجع رموز الإحالة والتجار المحالين.','اعتمد على حالات الأرباح والأهلية القادمة من الخادم.','في السحب أو الدفعات اتبع حالة الخدمة المعتمدة فقط.'], note:'لا يجب أن تحسب الواجهة العمولة أو أهلية السحب بنفسها.' },
    { id:'reports', title:'التقارير', summary:'تساعد التقارير في تحليل الحجم وحالات الدفع عبر الزمن.', steps:['حدد النطاق الزمني وانتبه للوقت والمنطقة الزمنية.','راجع الحجم وعدد المعاملات والنجاح والفشل والتسوية معًا.','استخدم بيانات الخادم المسجلة للقرارات المالية.'], note:'الرسوم البيانية للتحليل وليست مصدرًا مستقلاً للحقيقة المالية.' },
    { id:'developer', title:'المطور وAPI Keys وWebhooks', summary:'قسم المطور هو مساحة التكامل التقني لأنظمة التاجر.', steps:['استخدم API Keys في بيئات آمنة ووفق الصلاحيات.','أدر Webhooks وسجل عمليات التسليم من قسم المطور.','اعتبر Webhooks إشعارات فقط؛ الحقيقة المالية تأتي من التحقق والخادم.'], note:'لا توضع أسرار API أو Webhook في الروابط أو السجلات أو تخزين الواجهة أو القياس.' },
    { id:'security', title:'الأمان', summary:'يشمل هذا القسم حدود الوصول والتحقق من المحفظة وعناصر الأمان المهمة.', steps:['راجع حالة التحقق من المحفظة وصلاحيات التاجر.','استخدم الدعم للحوادث الأمنية أو رفض الوصول.','لا تضع عبارة الاسترداد أو المفتاح الخاص أو أسرار API أو Webhook في تذكرة أو التخزين المحلي.'], note:'التطبيق الفعلي للأمان يكون في المصادقة والتفويض وRLS على الخادم.' },
    { id:'tickets', title:'التذاكر والدعم', summary:'اقرأ مركز التدريب قبل إنشاء تذكرة؛ قد يمكن تحديد المشكلة من الحالة وتفاصيل Payment Intent.', steps:['اشرح المشكلة بوضوح ولا ترسل أي سر.','عند الحاجة أضف Payment ID أو Invoice ID أو Ticket ID أو توقيع المعاملة.','بعد الإنشاء تابع التذكرة في القائمة أدناه ورد على المحادثة.'], note:'مركز التدريب لا يلغي الدعم؛ يبقى إنشاء التذاكر وسجلها فعالين في أسفل الصفحة.' },
  ],
  ru: [
    { id:'onboarding', title:'Начало и настройка Merchant', summary:'Для приёма платежей нужен активный аккаунт, Merchant и подтверждённый кошелёк приёма.', steps:['Откройте Merchant и кошелёк приёма и создайте или проверьте данные бизнеса.','Подключите существующий кошелёк или создайте выделенный кошелёк SolMint и сохраните фразу восстановления безопасно.','Пройдите серверную проверку владения кошельком; принимать платежи может только подтверждённый кошелёк.'], note:'SolMint не хранит фразу восстановления или приватный ключ на сервере. Состояние Merchant и кошелька приходит из официального сервиса.' },
    { id:'account-wallet', title:'Аккаунт и кошелёк', summary:'Нажмите на область имени и кошелька в шапке, чтобы увидеть данные аккаунта и баланс кошелька приёма.', steps:['Баланс SOL, USDT и USDC читается из сети Solana через сервис Pay.','Проверьте адрес кошелька и время наблюдения; сетевые данные могут немного устареть.','Используйте кнопку выхода для завершения текущей сессии.'], note:'Показанный баланс — это снимок сети и не определяет самостоятельно бухгалтерское состояние Merchant или расчёты.' },
    { id:'overview', title:'Обзор и Dashboard', summary:'Dashboard показывает готовность Merchant и основные операционные данные.', steps:['Сначала проверьте статус Merchant и готовность кошелька приёма.','Для финансовых и операционных показателей используйте данные официального сервиса Pay.','Для деталей откройте Transactions, Invoices, Payment Links или Reports.'], note:'Frontend не вычисляет авторитетную финансовую истину; её источники — Backend и Database.' },
    { id:'checkout', title:'Оплата и Checkout', summary:'Checkout отображает Payment Intent и обеспечивает клиентский сценарий оплаты.', steps:['Откройте корректный Payment Intent и проверьте сумму, актив, адрес, комиссии и срок действия.','Отправьте транзакцию из кошелька клиента; отправка сама по себе не означает успешную оплату.','Дождитесь серверной проверки и следуйте авторитетному статусу платежа.'], note:'Отправлено, обнаружено, проверяется, подтверждено и завершено — разные состояния.' },
    { id:'transactions', title:'Transactions', summary:'Transactions — рабочий центр поиска и проверки платежей.', steps:['Ищите по Payment ID, подписи, клиенту или статусу.','Проверяйте сумму, актив, комиссию, settlement и временные метки.','Для underpaid, overpaid, неверного актива, неверного адресата или ambiguous используйте авторитетный статус.'], note:'Подпись или reference сами по себе не доказывают оплату.' },
    { id:'customers', title:'Customers', summary:'Здесь отображаются клиенты, связанные с платежами Merchant.', steps:['Просматривайте данные клиента, полученные от сервиса Pay.','Связывайте клиента с платежом через Payment ID или данные транзакции.','Разбирайте спорные случаи по данным Backend, а не по локальному состоянию UI.'], note:'Данные клиентов должны оставаться в границах авторизации Merchant.' },
    { id:'billing-links', title:'Invoices и Payment Links', summary:'Здесь создаются и управляются счета и многоразовые ссылки фиксированной оплаты.', steps:['Для Invoice укажите сумму, актив, описание и срок действия из доступной формы.','Для Payment Link настройте slug, название, фиксированную сумму, актив, плательщика комиссии и язык Checkout.','Публичную ссылку можно разместить в Telegram, мессенджере или на сайте; клиенту не нужен аккаунт SolMint.'], note:'Публичный Checkout собирает имя, фамилию и причину платежа и сохраняет их вместе с Payment Intent на сервере.' },
    { id:'referrals', title:'Referrals и партнёрство', summary:'Раздел содержит данные рефералов и партнёрства.', steps:['Проверяйте реферальный код и привлечённых Merchant.','Используйте только серверные статусы earnings и eligibility.','Для вывода или выплат ориентируйтесь на авторитетное состояние сервиса.'], note:'Frontend не должен самостоятельно рассчитывать комиссию или право на вывод.' },
    { id:'reports', title:'Reports', summary:'Reports помогает анализировать объём и состояния платежей по времени.', steps:['Выберите период и учитывайте timestamp и timezone.','Смотрите объём, количество операций, успех/ошибки и settlement вместе.','Для финансовых решений используйте данные, сохранённые Backend.'], note:'Графики — инструмент анализа, а не отдельный источник финансовой истины.' },
    { id:'developer', title:'Developer, API Keys и Webhooks', summary:'Developer предназначен для технической интеграции систем Merchant.', steps:['Используйте API Keys только в безопасной среде и согласно scope.','Управляйте Webhook endpoint и историей доставок из Developer.','Считайте Webhook уведомлением, а не финансовой истиной; статус платежа приходит из verification и Backend.'], note:'API secrets и Webhook secrets нельзя помещать в URL, логи, хранилище frontend или telemetry.' },
    { id:'security', title:'Безопасность', summary:'Здесь находятся проверки доступа, состояния кошелька и ключевые security controls.', steps:['Проверяйте Wallet Verification и доступ Merchant.','Для инцидентов безопасности используйте Support.','Никогда не помещайте seed phrase, private key, API secret или webhook secret в тикет или browser storage.'], note:'Реальное применение безопасности находится в Backend authentication, authorization и RLS.' },
    { id:'tickets', title:'Тикеты и поддержка', summary:'Перед созданием тикета изучите этот учебный центр; многие проблемы видны по статусу и деталям Payment Intent.', steps:['Опишите проблему точно и не передавайте секреты.','При необходимости укажите Payment ID, Invoice ID, Ticket ID или подпись транзакции.','После создания отслеживайте тикет в списке ниже и отвечайте в диалоге.'], note:'Учебный центр не заменяет поддержку; создание и история тикетов остаются активными ниже.' },
  ],
} as const satisfies Record<PayLocale, readonly PayTrainingTopic[]>;

export function trainingT(locale: PayLocale): TrainingMessages {
  return {
    title: locale === 'fa-IR' ? 'مرکز آموزش SolMint Pay' : locale === 'ar' ? 'مركز تدريب SolMint Pay' : locale === 'ru' ? 'Учебный центр SolMint Pay' : 'SolMint Pay Training Center',
    subtitle: locale === 'fa-IR' ? 'راهنمای استفاده از بخش‌های اصلی درگاه، قبل از ثبت تیکت' : locale === 'ar' ? 'دليل الأقسام الرئيسية في البوابة قبل إنشاء التذكرة' : locale === 'ru' ? 'Руководство по основным разделам Pay перед созданием тикета' : 'Guide to the main Pay areas before creating a support ticket',
    readBeforeTicket: locale === 'fa-IR' ? 'ابتدا موضوع مرتبط را بخوانید؛ سپس در صورت باقی‌ماندن مشکل، تیکت را در پایین صفحه ثبت کنید.' : locale === 'ar' ? 'اقرأ الموضوع المناسب أولاً، ثم أنشئ تذكرة في أسفل الصفحة إذا بقيت المشكلة.' : locale === 'ru' ? 'Сначала изучите нужный раздел, затем создайте тикет ниже, если проблема остаётся.' : 'Read the relevant topic first, then create a ticket below if the problem remains.',
    topicCount: (count) => locale === 'fa-IR' ? `${count} راهنما` : locale === 'ar' ? `${count} أدلة` : locale === 'ru' ? `${count} разделов` : `${count} guides`,
    topics: topics[locale],
  };
}
