import type { PayLocale } from '../types';

const messages = {
  'fa-IR': { title:'پشتیبانی و تیکت‌ها', subtitle:'درخواست‌های پشتیبانی Merchant و پاسخ‌های تیم SolMint', newTicket:'تیکت جدید', subject:'موضوع', message:'شرح درخواست', priority:'اولویت', normal:'عادی', high:'زیاد', urgent:'فوری', send:'ارسال تیکت', reply:'ارسال پاسخ', tickets:'تیکت‌ها', details:'جزئیات', noTickets:'هنوز تیکتی ثبت نشده است.', selectTicket:'برای مشاهده گفتگو یک تیکت را انتخاب کنید.', loading:'در حال بارگذاری…', retry:'تلاش دوباره', unauthorized:'برای مشاهده تیکت‌ها باید وارد حساب شوید.', forbidden:'دسترسی به این تیکت مجاز نیست.', error:'بارگذاری تیکت‌ها انجام نشد.', sent:'تیکت با موفقیت ثبت شد.', replied:'پاسخ ارسال شد.', status:'وضعیت', open:'باز', pendingCustomer:'در انتظار Merchant', pendingAdmin:'در انتظار پشتیبانی', resolved:'حل‌شده', closed:'بسته', updateStatus:'تغییر وضعیت', closeTicket:'بستن تیکت', reopenTicket:'بازگشایی', adminInbox:'صندوق پشتیبانی', adminOnly:'این بخش فقط برای ادمین وبسایت فعال است.', merchant:'Merchant', admin:'پشتیبانی SolMint', conversation:'گفتگو', sendError:'ارسال انجام نشد.', statusError:'تغییر وضعیت انجام نشد.', subjectHint:'حداقل ۳ و حداکثر ۱۶۰ کاراکتر', messageHint:'حداقل ۱ و حداکثر ۱۰۰۰۰ کاراکتر', priorityHelp:'برای اولویت‌بندی داخلی پشتیبانی استفاده می‌شود.', stale:'اطلاعات ممکن است قدیمی باشد؛ دوباره بارگذاری کنید.' },
  'en-US': { title:'Support & Tickets', subtitle:'Merchant support requests and SolMint replies', newTicket:'New ticket', subject:'Subject', message:'Message', priority:'Priority', normal:'Normal', high:'High', urgent:'Urgent', send:'Create ticket', reply:'Send reply', tickets:'Tickets', details:'Details', noTickets:'No support tickets yet.', selectTicket:'Select a ticket to view the conversation.', loading:'Loading…', retry:'Retry', unauthorized:'Sign in to view support tickets.', forbidden:'You are not allowed to access this ticket.', error:'Unable to load support tickets.', sent:'Ticket created successfully.', replied:'Reply sent.', status:'Status', open:'Open', pendingCustomer:'Waiting for merchant', pendingAdmin:'Waiting for support', resolved:'Resolved', closed:'Closed', updateStatus:'Change status', closeTicket:'Close ticket', reopenTicket:'Reopen', adminInbox:'Support inbox', adminOnly:'This area is available to website administrators only.', merchant:'Merchant', admin:'SolMint Support', conversation:'Conversation', sendError:'Message could not be sent.', statusError:'Status update failed.', subjectHint:'3–160 characters', messageHint:'1–10000 characters', priorityHelp:'Used for internal support prioritization.', stale:'Information may be stale; reload to refresh.' },
  'ar': { title:'الدعم والتذاكر', subtitle:'طلبات دعم التاجر وردود فريق SolMint', newTicket:'تذكرة جديدة', subject:'الموضوع', message:'الرسالة', priority:'الأولوية', normal:'عادي', high:'مرتفع', urgent:'عاجل', send:'إنشاء التذكرة', reply:'إرسال الرد', tickets:'التذاكر', details:'التفاصيل', noTickets:'لا توجد تذاكر بعد.', selectTicket:'اختر تذكرة لعرض المحادثة.', loading:'جارٍ التحميل…', retry:'إعادة المحاولة', unauthorized:'سجّل الدخول لعرض التذاكر.', forbidden:'ليس لديك صلاحية للوصول إلى هذه التذكرة.', error:'تعذر تحميل التذاكر.', sent:'تم إنشاء التذكرة بنجاح.', replied:'تم إرسال الرد.', status:'الحالة', open:'مفتوحة', pendingCustomer:'بانتظار التاجر', pendingAdmin:'بانتظار الدعم', resolved:'تم الحل', closed:'مغلقة', updateStatus:'تغيير الحالة', closeTicket:'إغلاق التذكرة', reopenTicket:'إعادة الفتح', adminInbox:'صندوق الدعم', adminOnly:'هذا القسم متاح لمسؤولي الموقع فقط.', merchant:'التاجر', admin:'دعم SolMint', conversation:'المحادثة', sendError:'تعذر الإرسال.', statusError:'تعذر تغيير الحالة.', subjectHint:'من 3 إلى 160 حرفًا', messageHint:'من 1 إلى 10000 حرف', priorityHelp:'تُستخدم للأولوية الداخلية للدعم.', stale:'قد تكون المعلومات قديمة؛ أعد التحميل.' },
  'ru': { title:'Поддержка и тикеты', subtitle:'Запросы мерчанта и ответы команды SolMint', newTicket:'Новый тикет', subject:'Тема', message:'Сообщение', priority:'Приоритет', normal:'Обычный', high:'Высокий', urgent:'Срочный', send:'Создать тикет', reply:'Отправить ответ', tickets:'Тикеты', details:'Детали', noTickets:'Тикетов пока нет.', selectTicket:'Выберите тикет для просмотра переписки.', loading:'Загрузка…', retry:'Повторить', unauthorized:'Войдите в аккаунт для просмотра тикетов.', forbidden:'У вас нет доступа к этому тикету.', error:'Не удалось загрузить тикеты.', sent:'Тикет создан.', replied:'Ответ отправлен.', status:'Статус', open:'Открыт', pendingCustomer:'Ожидает мерчанта', pendingAdmin:'Ожидает поддержки', resolved:'Решён', closed:'Закрыт', updateStatus:'Изменить статус', closeTicket:'Закрыть тикет', reopenTicket:'Открыть снова', adminInbox:'Входящие поддержки', adminOnly:'Этот раздел доступен только администраторам сайта.', merchant:'Мерчант', admin:'Поддержка SolMint', conversation:'Переписка', sendError:'Не удалось отправить.', statusError:'Не удалось изменить статус.', subjectHint:'3–160 символов', messageHint:'1–10000 символов', priorityHelp:'Используется для внутренней приоритизации.', stale:'Данные могли устареть; обновите страницу.' }
} as const;

export type TicketTranslationKey = keyof typeof messages['fa-IR'];
export function ticketT(locale: PayLocale, key: TicketTranslationKey): string { return messages[locale][key]; }
