import type{PayLocale}from'../types';
const messages={
'fa-IR':{title:'گزارش‌ها',subtitle:'خلاصه گزارش از داده‌های authoritative پرداخت برای این پذیرنده.',refresh:'به‌روزرسانی',range:'بازه گزارش',today:'امروز',sevenDays:'۷ روز',thirtyDays:'۳۰ روز',ninetyDays:'۹۰ روز',custom:'دلخواه',from:'از',to:'تا',loading:'در حال دریافت گزارش…',unauthorized:'برای مشاهده گزارش وارد شوید.',forbidden:'به گزارش این پذیرنده دسترسی ندارید.',loadFailed:'دریافت گزارش ناموفق بود.',retry:'تلاش مجدد',stale:'آخرین گزارش معتبر نمایش داده می‌شود؛ دریافت جدید ناموفق بود.',backendSource:'منبع: Backend / Database',paymentIntents:'Payment Intentها',completed:'تکمیل‌شده',customers:'مشتریان',completedRate:'نرخ تکمیل',completedAmount:'مبلغ پرداخت‌های تکمیل‌شده (اتمیک)',netRevenue:'درآمد خالص ثبت‌شده (اتمیک)',statusSummary:'خلاصه وضعیت',daily:'روند روزانه',date:'روز',truthNote:'مبالغ و وضعیت‌ها از Backend/Database می‌آیند؛ Frontend هیچ مبلغ یا درآمدی را محاسبه نمی‌کند.',chooseDates:'برای گزارش دلخواه، تاریخ شروع و پایان را انتخاب کنید.'},
'en-US':{title:'Reports',subtitle:'Authoritative payment reporting for this merchant.',refresh:'Refresh',range:'Report range',today:'Today',sevenDays:'7 days',thirtyDays:'30 days',ninetyDays:'90 days',custom:'Custom',from:'From',to:'To',loading:'Loading report…',unauthorized:'Sign in to view reports.',forbidden:'You do not have access to these merchant reports.',loadFailed:'Reports could not be loaded.',retry:'Retry',stale:'Showing the last valid report because the latest refresh failed.',backendSource:'Source: Backend / Database',paymentIntents:'Payment Intents',completed:'Completed',customers:'Customers',completedRate:'Completion rate',completedAmount:'Completed payment amount (atomic)',netRevenue:'Recognized net revenue (atomic)',statusSummary:'Status summary',daily:'Daily trend',date:'Date',truthNote:'Amounts and statuses come from Backend/Database; the Frontend does not calculate payment amounts or revenue.',chooseDates:'Choose a start and end date for a custom report.'},
'ar':{title:'التقارير',subtitle:'تقارير الدفع المعتمدة لهذا التاجر.',refresh:'تحديث',range:'نطاق التقرير',today:'اليوم',sevenDays:'7 أيام',thirtyDays:'30 يوماً',ninetyDays:'90 يوماً',custom:'مخصص',from:'من',to:'إلى',loading:'جاري تحميل التقرير…',unauthorized:'سجّل الدخول لعرض التقارير.',forbidden:'ليس لديك صلاحية لعرض تقارير هذا التاجر.',loadFailed:'تعذر تحميل التقارير.',retry:'إعادة المحاولة',stale:'يتم عرض آخر تقرير موثوق لأن التحديث الأخير فشل.',backendSource:'المصدر: Backend / Database',paymentIntents:'Payment Intents',completed:'مكتمل',customers:'العملاء',completedRate:'معدل الإكمال',completedAmount:'مبلغ المدفوعات المكتملة (atomic)',netRevenue:'صافي الإيراد المسجل (atomic)',statusSummary:'ملخص الحالات',daily:'الاتجاه اليومي',date:'التاريخ',truthNote:'المبالغ والحالات تأتي من Backend/Database؛ لا يحسب Frontend مبالغ الدفع أو الإيرادات.',chooseDates:'اختر تاريخ البداية والنهاية للتقرير المخصص.'},
'ru':{title:'Отчёты',subtitle:'Авторитетные данные о платежах этого мерчанта.',refresh:'Обновить',range:'Период отчёта',today:'Сегодня',sevenDays:'7 дней',thirtyDays:'30 дней',ninetyDays:'90 дней',custom:'Пользовательский',from:'С',to:'По',loading:'Загрузка отчёта…',unauthorized:'Войдите, чтобы открыть отчёты.',forbidden:'У вас нет доступа к отчётам этого мерчанта.',loadFailed:'Не удалось загрузить отчёты.',retry:'Повторить',stale:'Показан последний достоверный отчёт; обновление не удалось.',backendSource:'Источник: Backend / Database',paymentIntents:'Payment Intent',completed:'Завершено',customers:'Клиенты',completedRate:'Доля завершённых',completedAmount:'Сумма завершённых платежей (atomic)',netRevenue:'Признанный чистый доход (atomic)',statusSummary:'Сводка статусов',daily:'Динамика по дням',date:'Дата',truthNote:'Суммы и статусы поступают из Backend/Database; Frontend не рассчитывает суммы платежей или доход.',chooseDates:'Выберите начало и конец для пользовательского отчёта.'}
}as const;
type Key=keyof typeof messages['fa-IR'];
export function reportT(locale:PayLocale,key:Key){return messages[locale][key]}
