import type { PayLocale } from '../types';

type MerchantOnboardingMessages = {
  merchant: string; onboardingTitle: string; businessName: string; businessNamePlaceholder: string; businessSlug: string; businessSlugPlaceholder: string;
  createMerchant: string; checkExistingMerchant: string; loadMerchantFailed: string; businessNameRequired: string; slugInvalid: string; merchantCreationFailed: string;
  compatibleWalletRequired: string; walletAddressMissing: string; walletSignatureMissing: string; walletVerificationFailed: string; walletVerificationRejected: string;
  receiveWallet: string; walletNotVerified: string; connectAndVerifyWallet: string; verified: string; walletOwnershipVerified: string; walletSignatureRequest: string;
  signatureNotTransaction: string; copied: string; copy: string; close: string; merchantId: string; status: string;
};

const messages: Record<PayLocale, MerchantOnboardingMessages> = {
  'fa-IR': {
    merchant: 'Merchant', onboardingTitle: 'راه‌اندازی دریافت پرداخت', businessName: 'نام کسب‌وکار', businessNamePlaceholder: 'مثلاً SolMint Store', businessSlug: 'شناسه کسب‌وکار', businessSlugPlaceholder: 'solmint-store', createMerchant: 'ساخت Merchant', checkExistingMerchant: 'بررسی Merchant موجود', loadMerchantFailed: 'بارگذاری Merchant انجام نشد.', businessNameRequired: 'نام کسب‌وکار را وارد کنید.', slugInvalid: 'شناسه کسب‌وکار باید انگلیسی و بین ۳ تا ۶۰ کاراکتر باشد.', merchantCreationFailed: 'ساخت Merchant انجام نشد.', compatibleWalletRequired: 'کیف پول Solana سازگار با مرورگر پیدا نشد.', walletAddressMissing: 'آدرس کیف پول دریافت نشد.', walletSignatureMissing: 'امضای کیف پول دریافت نشد.', walletVerificationFailed: 'تأیید کیف پول انجام نشد.', walletVerificationRejected: 'مالکیت کیف پول تأیید نشد.', receiveWallet: 'کیف پول دریافت', walletNotVerified: 'هنوز تأیید نشده است', connectAndVerifyWallet: 'اتصال و تأیید کیف پول', verified: 'تأیید شد', walletOwnershipVerified: 'مالکیت کیف پول با امضای یک‌بارمصرف تأیید شد.', walletSignatureRequest: 'درخواست امضای کیف پول', signatureNotTransaction: 'این پیام تراکنش مالی نیست و فقط برای اثبات مالکیت همین کیف پول صادر شده است.', copied: 'کپی شد', copy: 'کپی پیام', close: 'بستن', merchantId: 'شناسه Merchant', status: 'وضعیت',
  },
  'en-US': {
    merchant: 'Merchant', onboardingTitle: 'Set up payment receiving', businessName: 'Business name', businessNamePlaceholder: 'e.g. SolMint Store', businessSlug: 'Business identifier', businessSlugPlaceholder: 'solmint-store', createMerchant: 'Create Merchant', checkExistingMerchant: 'Check existing Merchant', loadMerchantFailed: 'Unable to load the Merchant.', businessNameRequired: 'Enter a business name.', slugInvalid: 'The business identifier must be English and 3–60 characters long.', merchantCreationFailed: 'Merchant creation failed.', compatibleWalletRequired: 'No browser-compatible Solana wallet was found.', walletAddressMissing: 'The wallet address was not returned.', walletSignatureMissing: 'The wallet signature was not returned.', walletVerificationFailed: 'Wallet verification failed.', walletVerificationRejected: 'Wallet ownership could not be verified.', receiveWallet: 'Receiving wallet', walletNotVerified: 'Not verified yet', connectAndVerifyWallet: 'Connect and verify wallet', verified: 'Verified', walletOwnershipVerified: 'Wallet ownership was verified with a one-time signature.', walletSignatureRequest: 'Wallet signature request', signatureNotTransaction: 'This message is not a financial transaction. It only proves ownership of this wallet.', copied: 'Copied', copy: 'Copy message', close: 'Close', merchantId: 'Merchant ID', status: 'Status',
  },
  ar: {
    merchant: 'Merchant', onboardingTitle: 'إعداد استقبال المدفوعات', businessName: 'اسم النشاط التجاري', businessNamePlaceholder: 'مثال: SolMint Store', businessSlug: 'معرّف النشاط التجاري', businessSlugPlaceholder: 'solmint-store', createMerchant: 'إنشاء Merchant', checkExistingMerchant: 'فحص Merchant موجود', loadMerchantFailed: 'تعذر تحميل Merchant.', businessNameRequired: 'أدخل اسم النشاط التجاري.', slugInvalid: 'يجب أن يكون المعرّف باللغة الإنجليزية وبطول من 3 إلى 60 حرفًا.', merchantCreationFailed: 'تعذر إنشاء Merchant.', compatibleWalletRequired: 'لم يتم العثور على محفظة Solana متوافقة مع المتصفح.', walletAddressMissing: 'لم يتم إرجاع عنوان المحفظة.', walletSignatureMissing: 'لم يتم إرجاع توقيع المحفظة.', walletVerificationFailed: 'فشل التحقق من المحفظة.', walletVerificationRejected: 'تعذر التحقق من ملكية المحفظة.', receiveWallet: 'محفظة الاستلام', walletNotVerified: 'لم يتم التحقق بعد', connectAndVerifyWallet: 'توصيل المحفظة والتحقق منها', verified: 'تم التحقق', walletOwnershipVerified: 'تم التحقق من ملكية المحفظة بتوقيع لمرة واحدة.', walletSignatureRequest: 'طلب توقيع المحفظة', signatureNotTransaction: 'هذه الرسالة ليست معاملة مالية، بل تثبت ملكية هذه المحفظة فقط.', copied: 'تم النسخ', copy: 'نسخ الرسالة', close: 'إغلاق', merchantId: 'معرّف Merchant', status: 'الحالة',
  },
  ru: {
    merchant: 'Merchant', onboardingTitle: 'Настройка приёма платежей', businessName: 'Название бизнеса', businessNamePlaceholder: 'например, SolMint Store', businessSlug: 'Идентификатор бизнеса', businessSlugPlaceholder: 'solmint-store', createMerchant: 'Создать Merchant', checkExistingMerchant: 'Проверить Merchant', loadMerchantFailed: 'Не удалось загрузить Merchant.', businessNameRequired: 'Введите название бизнеса.', slugInvalid: 'Идентификатор должен быть на английском языке и содержать от 3 до 60 символов.', merchantCreationFailed: 'Не удалось создать Merchant.', compatibleWalletRequired: 'Совместимый с браузером кошелёк Solana не найден.', walletAddressMissing: 'Адрес кошелька не получен.', walletSignatureMissing: 'Подпись кошелька не получена.', walletVerificationFailed: 'Не удалось подтвердить кошелёк.', walletVerificationRejected: 'Не удалось подтвердить владение кошельком.', receiveWallet: 'Кошелёк для получения', walletNotVerified: 'Пока не подтверждён', connectAndVerifyWallet: 'Подключить и подтвердить кошелёк', verified: 'Подтверждено', walletOwnershipVerified: 'Владение кошельком подтверждено одноразовой подписью.', walletSignatureRequest: 'Запрос подписи кошелька', signatureNotTransaction: 'Это сообщение не является финансовой транзакцией. Оно только подтверждает владение этим кошельком.', copied: 'Скопировано', copy: 'Копировать сообщение', close: 'Закрыть', merchantId: 'ID Merchant', status: 'Статус',
  },
};

export function translateMerchantOnboarding(locale: PayLocale, key: keyof MerchantOnboardingMessages): string {
  return messages[locale][key];
}
