import type { PayLocale } from '../types';
import type { PayInvoiceFeePayer, PayInvoiceStatus } from '../services/invoiceService';

const messages={
'fa-IR':{title:'فاکتورها',subtitle:'فاکتورهای واقعی ثبت‌شده برای این پذیرنده.',search:'جستجو در شماره فاکتور، عنوان یا مشتری',all:'همه وضعیت‌ها',refresh:'به‌روزرسانی',details:'جزئیات',noData:'هنوز فاکتوری برای نمایش وجود ندارد.',loadFailed:'دریافت فاکتورها ناموفق بود.',retry:'تلاش مجدد',unauthorized:'برای مشاهده فاکتورها وارد شوید.',forbidden:'به فاکتورهای این پذیرنده دسترسی ندارید.',invoiceNumber:'شماره فاکتور',customer:'مشتری',titleField:'عنوان',amount:'مبلغ اتمیک',asset:'دارایی',selectAsset:'انتخاب دارایی',status:'وضعیت',dueAt:'سررسید',createdAt:'ایجاد شده',feePayer:'پرداخت‌کننده کارمزد',description:'توضیحات',close:'بستن',checkoutLocale:'زبان Checkout',autoLocale:'خودکار',createTitle:'ایجاد فاکتور',createDescription:'یک فاکتور جدید برای همین مرچنت ایجاد کنید.',createAction:'ایجاد فاکتور',creating:'در حال ایجاد…',created:'فاکتور ایجاد شد و در فهرست نمایش داده می‌شود.',createInvalid:'اطلاعات فاکتور کامل یا معتبر نیست.',createForbidden:'برای ایجاد فاکتور این مرچنت دسترسی ندارید.',createConflict:'این شماره فاکتور قبلاً برای این مرچنت ثبت شده است.',createFailed:'ایجاد فاکتور انجام نشد؛ دوباره تلاش کنید.',atomicHint:'مبلغ با واحد اتمیک و بدون اعشار ثبت می‌شود.',payer:{merchant:'پذیرنده',customer:'مشتری'},statuses:{draft:'پیش‌نویس',open:'باز',paid:'پرداخت‌شده',partially_paid:'نیمه‌پرداخت',overdue:'سررسیدگذشته',void:'باطل',refunded:'بازپرداخت‌شده'}},
'en-US':{title:'Invoices',subtitle:'Real invoices recorded for this merchant.',search:'Search invoice number, title or customer',all:'All statuses',refresh:'Refresh',details:'Details',noData:'No invoices to display.',loadFailed:'Invoices could not be loaded.',retry:'Retry',unauthorized:'Sign in to view invoices.',forbidden:'You do not have access to these merchant invoices.',invoiceNumber:'Invoice number',customer:'Customer',titleField:'Title',amount:'Atomic amount',asset:'Asset',selectAsset:'Select asset',status:'Status',dueAt:'Due',createdAt:'Created',feePayer:'Fee payer',description:'Description',close:'Close',checkoutLocale:'Checkout locale',autoLocale:'Auto',createTitle:'Create invoice',createDescription:'Create a new invoice for this merchant.',createAction:'Create invoice',creating:'Creating…',created:'Invoice created and added to the list.',createInvalid:'Invoice data is incomplete or invalid.',createForbidden:'You cannot create invoices for this merchant.',createConflict:'That invoice number already exists for this merchant.',createFailed:'Invoice could not be created. Retry.',atomicHint:'Amount is entered as an integer atomic value with no decimals.',payer:{merchant:'Merchant',customer:'Customer'},statuses:{draft:'Draft',open:'Open',paid:'Paid',partially_paid:'Partially paid',overdue:'Overdue',void:'Void',refunded:'Refunded'}},
'ar':{title:'الفواتير',subtitle:'الفواتير الحقيقية المسجلة لهذا التاجر.',search:'ابحث برقم الفاتورة أو العنوان أو العميل',all:'كل الحالات',refresh:'تحديث',details:'التفاصيل',noData:'لا توجد فواتير للعرض.',loadFailed:'تعذر تحميل الفواتير.',retry:'إعادة المحاولة',unauthorized:'سجّل الدخول لعرض الفواتير.',forbidden:'لا تملك صلاحية الوصول إلى فواتير هذا التاجر.',invoiceNumber:'رقم الفاتورة',customer:'العميل',titleField:'العنوان',amount:'المبلغ الذري',asset:'الأصل',selectAsset:'اختر الأصل',status:'الحالة',dueAt:'الاستحقاق',createdAt:'أُنشئت',feePayer:'دافع الرسوم',description:'الوصف',close:'إغلاق',checkoutLocale:'لغة Checkout',autoLocale:'تلقائي',createTitle:'إنشاء فاتورة',createDescription:'أنشئ فاتورة جديدة لهذا التاجر.',createAction:'إنشاء الفاتورة',creating:'جارٍ الإنشاء…',created:'تم إنشاء الفاتورة وإضافتها إلى القائمة.',createInvalid:'بيانات الفاتورة غير مكتملة أو غير صالحة.',createForbidden:'لا تملك صلاحية إنشاء فواتير لهذا التاجر.',createConflict:'رقم الفاتورة هذا موجود بالفعل لهذا التاجر.',createFailed:'تعذر إنشاء الفاتورة. أعد المحاولة.',atomicHint:'يُدخل المبلغ كقيمة ذرية صحيحة بدون كسور.',payer:{merchant:'التاجر',customer:'العميل'},statuses:{draft:'مسودة',open:'مفتوحة',paid:'مدفوعة',partially_paid:'مدفوعة جزئياً',overdue:'متأخرة',void:'ملغاة',refunded:'مستردة'}},
'ru':{title:'Счета',subtitle:'Реальные счета, зарегистрированные для этого мерчанта.',search:'Поиск по номеру счёта, названию или клиенту',all:'Все статусы',refresh:'Обновить',details:'Подробности',noData:'Нет счетов для отображения.',loadFailed:'Не удалось загрузить счета.',retry:'Повторить',unauthorized:'Войдите, чтобы видеть счета.',forbidden:'У вас нет доступа к счетам этого мерчанта.',invoiceNumber:'Номер счёта',customer:'Клиент',titleField:'Название',amount:'Сумма в atomic units',asset:'Актив',selectAsset:'Выберите актив',status:'Статус',dueAt:'Срок',createdAt:'Создано',feePayer:'Плательщик комиссии',description:'Описание',close:'Закрыть',checkoutLocale:'Язык Checkout',autoLocale:'Авто',createTitle:'Создать счёт',createDescription:'Создайте новый счёт для этого мерчанта.',createAction:'Создать счёт',creating:'Создание…',created:'Счёт создан и добавлен в список.',createInvalid:'Данные счёта неполные или недействительны.',createForbidden:'У вас нет права создавать счета для этого мерчанта.',createConflict:'Этот номер счёта уже существует у этого мерчанта.',createFailed:'Не удалось создать счёт. Повторите попытку.',atomicHint:'Сумма вводится как целое значение atomic units без дробей.',payer:{merchant:'Мерчант',customer:'Клиент'},statuses:{draft:'Черновик',open:'Открыт',paid:'Оплачен',partially_paid:'Частично оплачен',overdue:'Просрочен',void:'Аннулирован',refunded:'Возвращён'}}
} as const;
export type InvoiceTranslationKey=Exclude<keyof typeof messages['fa-IR'],'payer'|'statuses'>;
export function invoiceT(locale:PayLocale,key:InvoiceTranslationKey):string{return messages[locale][key];}
export function invoiceStatusT(locale:PayLocale,status:PayInvoiceStatus):string{return messages[locale].statuses[status];}
export function invoicePayerT(locale:PayLocale,payer:PayInvoiceFeePayer):string{return messages[locale].payer[payer];}
