import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Config = { provider:'github'; githubOwner:string; githubRepository:string; branch:string; basePath:string; connectionStatus?:string; lastTestAt?:string|null };
const SUPABASE_URL=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const GITHUB_TOKEN=(Deno.env.get('GITHUB_MEDIA_TOKEN')||'').trim();
const DEFAULT_CONFIG:Config={provider:'github',githubOwner:'azad2022',githubRepository:'solsite',branch:'main',basePath:'public/media/articles/',connectionStatus:'untested',lastTestAt:null};
const MAX_UPLOAD_BYTES=8*1024*1024;
const IMAGE_EXTENSIONS=new Set(['.jpg','.jpeg','.png','.webp','.gif','.svg','.avif']);
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-admin-passcode','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}});
const ok=(data:Record<string,unknown>)=>({success:true,timestamp:new Date().toISOString(),...data});
const fail=(code:string,stage:string,message:string,details:Record<string,unknown>={})=>({success:false,errorCode:code,stage,message,details,timestamp:new Date().toISOString()});
function cleanPath(v:string){const s=String(v||'').trim().replace(/^\/+|\/+$/g,'');return s?`${s}/`:''}
function config(v:any):Config{return{provider:'github',githubOwner:String(v?.githubOwner||DEFAULT_CONFIG.githubOwner).trim().replace(/[^A-Za-z0-9_.-]/g,''),githubRepository:String(v?.githubRepository||DEFAULT_CONFIG.githubRepository).trim().replace(/[^A-Za-z0-9_.-]/g,''),branch:String(v?.branch||DEFAULT_CONFIG.branch).trim().replace(/[^A-Za-z0-9._\/-]/g,''),basePath:cleanPath(v?.basePath||DEFAULT_CONFIG.basePath),connectionStatus:v?.connectionStatus||'untested',lastTestAt:v?.lastTestAt??null}}
function imagePath(p:string){const x=p.toLowerCase();return [...IMAGE_EXTENSIONS].some(e=>x.endsWith(e))}
function safePath(p:string){const x=String(p||'').replace(/\\/g,'/');return !x||x.startsWith('/')||x.includes('..')||x.includes('//')?null:x}
function ghHeaders(){if(!GITHUB_TOKEN)throw new Error('GITHUB_MEDIA_TOKEN is not configured on the server.');return{Accept:'application/vnd.github+json',Authorization:`Bearer ${GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'Solmint-GitHub-Media-Gateway'}}
async function gh(path:string,init:RequestInit={}){return fetch(`https://api.github.com${path}`,{...init,headers:{...ghHeaders(),...(init.headers||{})}})}
async function sb(path:string,init:RequestInit={}){if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error('Supabase service environment is not configured.');return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json',...(init.headers||{})}})}
async function body(r:Response){const t=await r.text();if(!t)return null;try{return JSON.parse(t)}catch{return{raw:t}}}
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function authenticate(req:Request){const supplied=(req.headers.get('x-admin-passcode')||'').trim();if(!supplied)return false;const r=await sb('users?username=eq.admin&is_active=eq.true&select=password_hash,role&limit=1');if(!r.ok)return false;const rows=await body(r);const u=Array.isArray(rows)?rows[0]:null;if(!u||!['admin','superadmin'].includes(String(u.role)))return false;const hashed=await sha256(supplied);return supplied===u.password_hash||hashed===u.password_hash}
async function getConfig(){const r=await sb('media_config?id=eq.active_config&select=*');if(!r.ok)return{...DEFAULT_CONFIG};const rows=await body(r);return config(Array.isArray(rows)&&rows[0]?rows[0]:DEFAULT_CONFIG)}
async function saveConfig(c:Config){const n=config(c);const r=await sb('media_config?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:'active_config',...n,last_test_at:n.connectionStatus==='connected'?new Date().toISOString():null})});if(!r.ok)throw new Error(`Supabase media config save failed (${r.status}).`);return n}
async function saveAsset(a:any){const row={id:a.id,provider:'github',github_owner:a.githubOwner,github_repository:a.githubRepository,branch:a.branch,path:a.path,filename:a.filename,public_url:a.publicUrl,mime_type:a.mimeType,file_size:a.fileSize||0,width:a.width||0,height:a.height||0,sha:a.sha||null,original_filename:a.originalFilename||a.filename,alt_text:a.altText||'',title:a.title||'',updated_at:new Date().toISOString()};const r=await sb('media_assets?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});if(!r.ok)throw new Error(`Supabase media asset save failed (${r.status}).`)}
async function deleteMeta(id:string){if(id)await sb(`media_assets?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'})}
async function metadata(c:Config){const q=new URLSearchParams({github_owner:`eq.${c.githubOwner}`,github_repository:`eq.${c.githubRepository}`,branch:`eq.${c.branch}`,select:'*',limit:'1000'});const r=await sb(`media_assets?${q}`);if(!r.ok)return[];const x=await body(r);return Array.isArray(x)?x:[]}
function asset(row:any,f:any){return{id:row?.id||f.id,provider:'github',githubOwner:row?.github_owner||f.githubOwner,githubRepository:row?.github_repository||f.githubRepository,branch:row?.branch||f.branch,path:row?.path||f.path,filename:row?.filename||f.filename,publicUrl:row?.public_url||f.publicUrl,mimeType:row?.mime_type||f.mimeType||'image/*',fileSize:row?.file_size||f.fileSize||0,width:row?.width||f.width||0,height:row?.height||f.height||0,sha:row?.sha||f.sha,createdAt:row?.created_at||f.createdAt||new Date().toISOString(),updatedAt:row?.updated_at||f.updatedAt,originalFilename:row?.original_filename||f.originalFilename||f.filename,altText:row?.alt_text||f.altText||'',title:row?.title||f.title||f.filename}}
async function repoCheck(c:Config){if(!GITHUB_TOKEN)return{ok:false,code:'GITHUB_TOKEN_MISSING',stage:'github_authentication',message:'کلید GitHub روی سرور تنظیم نشده است.',steps:[]};const steps:any[]=[{name:'GitHub Token',stage:'github_authentication',status:'passed',message:'Token روی سرور تنظیم شده است.'}];const rr=await gh(`/repos/${c.githubOwner}/${c.githubRepository}`);const rb=await body(rr);if(!rr.ok){const code=rr.status===401?'GITHUB_TOKEN_INVALID':rr.status===403?'GITHUB_TOKEN_PERMISSION_DENIED':'GITHUB_REPOSITORY_NOT_FOUND';const msg=rr.status===401?'Token معتبر نیست یا منقضی شده است.':rr.status===403?'Token معتبر است اما دسترسی کافی ندارد.':'Repository یافت نشد یا قابل دسترسی نیست.';steps.push({name:'GitHub Repository',stage:'github_repository_check',status:'failed',message:msg,details:{status:rr.status}});return{ok:false,code,stage:'github_repository_check',message:msg,details:{status:rr.status},steps}}steps.push({name:'GitHub Repository',stage:'github_repository_check',status:'passed',message:'Repository قابل دسترسی است.',details:{full_name:rb?.full_name,private:rb?.private}});const br=await gh(`/repos/${c.githubOwner}/${c.githubRepository}/branches/${encodeURIComponent(c.branch)}`);if(!br.ok){steps.push({name:'Branch',stage:'github_branch_check',status:'failed',message:`Branch ${c.branch} قابل دسترسی نیست.`,details:{status:br.status}});return{ok:false,code:'GITHUB_BRANCH_NOT_FOUND',stage:'github_branch_check',message:`Branch ${c.branch} قابل دسترسی نیست.`,details:{status:br.status},steps}}steps.push({name:'Branch',stage:'github_branch_check',status:'passed',message:'Branch قابل دسترسی است.'});const tr=await gh(`/repos/${c.githubOwner}/${c.githubRepository}/git/trees/${encodeURIComponent(c.branch)}?recursive=1`);const tb=await body(tr);if(!tr.ok)return{ok:false,code:'GITHUB_API_ERROR',stage:'media_directory_check',message:`خطای GitHub (${tr.status}).`,details:{status:tr.status},steps};const matches=(tb?.tree||[]).filter((i:any)=>i.type==='blob'&&String(i.path||'').startsWith(c.basePath)&&imagePath(String(i.path||''))).length;steps.push({name:'Media Directory',stage:'media_directory_check',status:matches?'passed':'warning',message:matches?'مسیر رسانه در مخزن پیدا شد.':'مسیر رسانه وجود دارد اما هنوز تصویر ندارد.',details:{basePath:c.basePath,matchedFiles:matches}});return{ok:true,steps,details:{repo:`${c.githubOwner}/${c.githubRepository}`,branch:c.branch,basePath:c.basePath}}}
async function list(c:Config){const r=await gh(`/repos/${c.githubOwner}/${c.githubRepository}/git/trees/${encodeURIComponent(c.branch)}?recursive=1`);if(!r.ok)throw new Error(`GitHub tree failed (${r.status}).`);const t=await body(r);if(t?.truncated)throw new Error('فهرست فایل‌های GitHub ناقص شد.');const rows=await metadata(c);const map=new Map(rows.map((x:any)=>[x.path,x]));return(t?.tree||[]).filter((i:any)=>i.type==='blob'&&String(i.path||'').startsWith(c.basePath)&&imagePath(String(i.path||''))).map((i:any)=>{const filename=i.path.split('/').pop()||i.path;const ep=i.path.split('/').map(encodeURIComponent).join('/');const f={id:`github_${c.githubOwner}_${c.githubRepository}_${i.sha}`,githubOwner:c.githubOwner,githubRepository:c.githubRepository,branch:c.branch,path:i.path,filename,publicUrl:`https://raw.githubusercontent.com/${c.githubOwner}/${c.githubRepository}/${encodeURIComponent(c.branch)}/${ep}`,mimeType:`image/${filename.split('.').pop()}`,fileSize:0,sha:i.sha,createdAt:new Date().toISOString(),originalFilename:filename,altText:'',title:filename};return asset(map.get(i.path),f)})}
async function upload(b:any,c:Config){const filename=String(b.filename||'').replace(/[^a-zA-Z0-9._-]/g,'');if(!filename||filename.includes('..'))throw new Error('نام فایل نامعتبر است.');const base64=String(b.base64||'');if(!base64)throw new Error('محتوای تصویر خالی است.');if(Math.floor(base64.length*3/4)>MAX_UPLOAD_BYTES)throw new Error('حجم تصویر بیش از ۸ مگابایت است.');const p=safePath(`${c.basePath}${filename}`);if(!p||!p.startsWith(c.basePath))throw new Error('مسیر فایل نامعتبر است.');const ep=`/repos/${c.githubOwner}/${c.githubRepository}/contents/${p.split('/').map(encodeURIComponent).join('/')}`;const old=await gh(`${ep}?ref=${encodeURIComponent(c.branch)}`);let oldSha='';if(old.ok){oldSha=(await body(old))?.sha||'';if(!b.overwrite)return{conflict:true,existingSha:oldSha,message:`فایلی با نام ${filename} در مخزن وجود دارد.`}}else if(old.status!==404)throw new Error(`خطا در بررسی فایل موجود (${old.status}).`);const put=await gh(ep,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Upload media asset: ${filename} via Solmint Admin`,content:base64,branch:c.branch,...(oldSha?{sha:oldSha}:{})})});if(!put.ok)throw new Error(`GitHub upload failed (${put.status}).`);const d=await body(put);const encoded=p.split('/').map(encodeURIComponent).join('/');const a={id:`asset_${Date.now()}_${crypto.randomUUID().slice(0,8)}`,provider:'github',githubOwner:c.githubOwner,githubRepository:c.githubRepository,branch:c.branch,path:p,filename,publicUrl:`https://raw.githubusercontent.com/${c.githubOwner}/${c.githubRepository}/${encodeURIComponent(c.branch)}/${encoded}`,mimeType:b.mimeType||'image/webp',fileSize:Math.floor(base64.length*3/4),width:Number(b.width||0),height:Number(b.height||0),sha:d?.content?.sha||oldSha,createdAt:new Date().toISOString(),originalFilename:b.originalFilename||filename,altText:b.altText||'',title:b.title||filename};await saveAsset(a);return{asset:a}}
async function remove(b:any,c:Config){const p=safePath(b.path);if(!p||!p.startsWith(c.basePath))throw new Error('مسیر فایل برای این کتابخانه معتبر نیست.');const ep=`/repos/${c.githubOwner}/${c.githubRepository}/contents/${p.split('/').map(encodeURIComponent).join('/')}`;const old=await gh(`${ep}?ref=${encodeURIComponent(c.branch)}`);if(old.status===404){await deleteMeta(b.assetId);return}if(!old.ok)throw new Error(`خطا در خواندن فایل برای حذف (${old.status}).`);const d=await body(old);const del=await gh(ep,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Delete media asset: ${p} via Solmint Admin`,sha:b.sha||d?.sha,branch:c.branch})});if(!del.ok)throw new Error(`GitHub delete failed (${del.status}).`);await deleteMeta(b.assetId)}
async function migrate(b:any,source:Config,target:Config){const sc=await repoCheck(source);if(!sc.ok)throw new Error(sc.message);const tc=await repoCheck(target);if(!tc.ok)throw new Error(tc.message);const assets=Array.isArray(b.assets)?b.assets:await list(source);const migrated:any[]=[];for(const a of assets){const sp=safePath(a.path);if(!sp||!sp.startsWith(source.basePath))throw new Error(`مسیر مبدا نامعتبر است: ${a.path}`);const se=`/repos/${source.githubOwner}/${source.githubRepository}/contents/${sp.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(source.branch)}`;const sr=await gh(se);if(!sr.ok)throw new Error(`خواندن ${a.filename} از مبدا ناموفق بود.`);const sd=await body(sr);const tp=`${target.basePath}${a.filename}`;const te=`/repos/${target.githubOwner}/${target.githubRepository}/contents/${tp.split('/').map(encodeURIComponent).join('/')}`;const ex=await gh(`${te}?ref=${encodeURIComponent(target.branch)}`);let sha='';if(ex.ok)sha=(await body(ex))?.sha||'';else if(ex.status!==404)throw new Error(`بررسی مقصد برای ${a.filename} ناموفق بود.`);const pr=await gh(te,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Migrate media asset: ${a.filename} via Solmint Admin`,content:sd?.content,branch:target.branch,...(sha?{sha}:{})})});if(!pr.ok)throw new Error(`نوشتن ${a.filename} در مقصد ناموفق بود.`);const pd=await body(pr);const encoded=tp.split('/').map(encodeURIComponent).join('/');migrated.push({...a,githubOwner:target.githubOwner,githubRepository:target.githubRepository,branch:target.branch,path:tp,publicUrl:`https://raw.githubusercontent.com/${target.githubOwner}/${target.githubRepository}/${encodeURIComponent(target.branch)}/${encoded}`,sha:pd?.content?.sha||sha})}for(const a of migrated)await saveAsset(a);await saveConfig({...target,connectionStatus:'connected',lastTestAt:new Date().toISOString()});return{migratedAssets:migrated,total:migrated.length}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json(fail('METHOD_NOT_ALLOWED','request_validation','Method Not Allowed'),405);try{if(!(await authenticate(req)))return json(fail('ADMIN_AUTHENTICATION_FAILED','admin_authentication','دسترسی غیرمجاز.'),401);const b=await req.json().catch(()=>({}));const action=String(b.action||'');let c=await getConfig();if(b.config)c=config(b.config);if(action==='get-config')return json(ok({config:c,hasToken:Boolean(GITHUB_TOKEN)}));if(action==='test'){const r=await repoCheck(c);if(!r.ok)return json(fail(r.code,r.stage,r.message,r.details),200);await saveConfig({...c,connectionStatus:'connected',lastTestAt:new Date().toISOString()});return json(ok({message:'اتصال به‌صورت کامل تأیید شد.',details:r.details,diagnostics:r.steps}))}if(action==='save-config'){const r=await repoCheck(c);if(!r.ok)return json(fail(r.code,r.stage,r.message,r.details),200);const saved=await saveConfig({...c,connectionStatus:'connected',lastTestAt:new Date().toISOString()});return json(ok({config:saved}))}if(action==='list')return json(ok({assets:await list(c),config:c}));if(action==='upload'){const r=await upload(b,c);if(r.conflict)return json(fail('FILE_EXISTS','github_upload',r.message,{existingSha:r.existingSha}),200);return json(ok({asset:r.asset,message:'تصویر با موفقیت در GitHub ذخیره شد.'}))}if(action==='delete'){await remove(b,c);return json(ok({message:'تصویر با موفقیت حذف شد.'}))}if(action==='migrate'){const target=config(b.targetConfig);const r=await migrate(b,c,target);return json(ok({message:`تمام ${r.total} تصویر با موفقیت به مقصد منتقل شد.`,...r}))}return json(fail('INVALID_ACTION','request_validation','عملیات رسانه نامعتبر است.'),400)}catch(e){console.error('github-media error',e);const m=e instanceof Error?e.message:'خطای ناشناخته سرور';return json(fail(m.includes('GITHUB_MEDIA_TOKEN')?'GITHUB_TOKEN_MISSING':'INTERNAL_SERVER_ERROR','server_runtime',m),500)}});
