import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Config={provider:'github';githubOwner:string;githubRepository:string;branch:string;basePath:string;connectionStatus?:string;lastTestAt?:string|null};
const URL=(Deno.env.get('SUPABASE_URL')||'https://nvopkbiedorfshwbmyhn.supabase.co').replace(/\/$/,'');
const DBKEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const GH=(Deno.env.get('GITHUB_MEDIA_TOKEN')||Deno.env.get('GITHUB_TOKEN')||'').trim();
const DEFAULT:Config={provider:'github',githubOwner:'azad2022',githubRepository:'solsite',branch:'main',basePath:'public/media/articles/',connectionStatus:'untested',lastTestAt:null};
const MAX=8*1024*1024;
const CORS={'Access-Control-Allow-Origin':'https://solmint.ir','Access-Control-Allow-Headers':'content-type,x-solmint-session','Access-Control-Allow-Methods':'POST,OPTIONS'};
const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...CORS,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const ok=(d:Record<string,unknown>)=>json({success:true,timestamp:new Date().toISOString(),...d});
const fail=(code:string,stage:string,message:string,details:Record<string,unknown>={},status=200)=>json({success:false,errorCode:code,stage,message,details,timestamp:new Date().toISOString()},status);
function clean(v:unknown){return String(v??'').trim()}
function cfg(v:any):Config{return{provider:'github',githubOwner:clean(v?.githubOwner||DEFAULT.githubOwner).replace(/[^A-Za-z0-9_.-]/g,''),githubRepository:clean(v?.githubRepository||DEFAULT.githubRepository).replace(/[^A-Za-z0-9_.-]/g,''),branch:clean(v?.branch||DEFAULT.branch).replace(/[^A-Za-z0-9._/-]/g,''),basePath:(clean(v?.basePath||DEFAULT.basePath).replace(/^\/+|\/+$/g,'')+'/'),connectionStatus:v?.connectionStatus||'untested',lastTestAt:v?.lastTestAt??null}}
async function sha(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function db(path:string,init:RequestInit={}){if(!DBKEY)throw new Error('MEDIA_DB_KEY_MISSING');return fetch(`${URL}/rest/v1/${path}`,{...init,headers:{apikey:DBKEY,Authorization:`Bearer ${DBKEY}`,'Content-Type':'application/json',...(init.headers||{})}})}
async function body(r:Response){const t=await r.text();try{return t?JSON.parse(t):null}catch{return null}}
async function auth(req:Request){const raw=(req.headers.get('x-solmint-session')||'').trim();if(!raw)return{ok:false,code:'MEDIA_ADMIN_SESSION_MISSING',stage:'session'};const h=await sha(raw);const s=await db(`auth_sessions?select=user_id,expires_at&token_hash=eq.${encodeURIComponent(h)}&limit=1`);if(!s.ok)throw new Error(`SESSION_LOOKUP_${s.status}`);const ss=await body(s);const row=Array.isArray(ss)?ss[0]:null;if(!row)return{ok:false,code:'MEDIA_ADMIN_SESSION_INVALID',stage:'session'};if(Date.parse(row.expires_at)<=Date.now())return{ok:false,code:'MEDIA_ADMIN_SESSION_EXPIRED',stage:'session'};const u=await db(`users?select=id,username,role,is_active&id=eq.${encodeURIComponent(row.user_id)}&limit=1`);if(!u.ok)throw new Error(`USER_LOOKUP_${u.status}`);const users=await body(u);const user=Array.isArray(users)?users[0]:null;if(!user)return{ok:false,code:'MEDIA_ADMIN_USER_NOT_FOUND',stage:'user_lookup'};if(user.is_active===false)return{ok:false,code:'MEDIA_ADMIN_INACTIVE',stage:'authorization'};if(!['admin','superadmin'].includes(String(user.role)))return{ok:false,code:'MEDIA_ADMIN_ROLE_DENIED',stage:'authorization'};await db(`auth_sessions?token_hash=eq.${encodeURIComponent(h)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({last_seen_at:new Date().toISOString()})}).catch(()=>{});return{ok:true,user}}
async function gh(path:string,init:RequestInit={}){if(!GH)throw new Error('GITHUB_TOKEN_MISSING');return fetch(`https://api.github.com${path}`,{...init,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${GH}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'Solmint-GitHub-Media',...(init.headers||{})}})}
function safePath(p:string){const x=String(p||'').replace(/\\/g,'/');return x&&!x.startsWith('/')&&!x.includes('..')&&!x.includes('//')?x:null}
function image(p:string){return ['.jpg','.jpeg','.png','.webp','.gif','.avif','.svg'].some(e=>p.toLowerCase().endsWith(e))}
async function getConfig(){const r=await db('media_config?id=eq.active_config&select=*');if(!r.ok)return DEFAULT;const a=await body(r);return cfg(Array.isArray(a)&&a[0]?a[0]:DEFAULT)}
async function saveConfig(c:Config){const r=await db('media_config?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:'active_config',provider:'github',github_owner:c.githubOwner,github_repository:c.githubRepository,branch:c.branch,base_path:c.basePath,connection_status:c.connectionStatus||'connected',last_test_at:c.connectionStatus==='connected'?new Date().toISOString():null})});if(!r.ok)throw new Error(`MEDIA_CONFIG_SAVE_${r.status}`)}
async function preflight(c:Config){if(!GH)return fail('GITHUB_TOKEN_MISSING','github_authentication','توکن GitHub در Edge Function تنظیم نشده است.');const r=await gh(`/repos/${c.githubOwner}/${c.githubRepository}`);const d=await body(r);if(!r.ok){const code=r.status===401?'GITHUB_TOKEN_INVALID':r.status===403?'GITHUB_TOKEN_PERMISSION_DENIED':r.status===404?'GITHUB_REPOSITORY_NOT_FOUND':'GITHUB_API_ERROR';return fail(code,'github_repository_check',`GitHub Repository قابل دسترسی نیست (${r.status}).`,{status:r.status,githubMessage:d?.message||null})}const b=await gh(`/repos/${c.githubOwner}/${c.githubRepository}/branches/${encodeURIComponent(c.branch)}`);if(!b.ok)return fail('GITHUB_BRANCH_NOT_FOUND','github_branch_check',`Branch «${c.branch}» قابل دسترسی نیست.`,{status:b.status});const push=Boolean(d?.permissions?.push);if(!push)return fail('GITHUB_WRITE_PERMISSION_REQUIRED','github_write_permission','توکن GitHub Repository را می‌خواند اما مجوز نوشتن ندارد. در Fine-grained PAT، دسترسی Contents را روی Read and write قرار دهید.',{repository:d?.full_name||`${c.githubOwner}/${c.githubRepository}`,permissions:d?.permissions||null});return ok({message:'اتصال GitHub، Repository، Branch و مجوز نوشتن با موفقیت تأیید شد.',details:{repo:d?.full_name,private:d?.private,branch:c.branch,basePath:c.basePath,writeAccess:true}})}
async function list(c:Config){const r=await gh(`/repos/${c.githubOwner}/${c.githubRepository}/git/trees/${encodeURIComponent(c.branch)}?recursive=1`);if(!r.ok)throw new Error(`GITHUB_TREE_${r.status}`);const t=await body(r);if(t?.truncated)throw new Error('GITHUB_TREE_TRUNCATED');return(t?.tree||[]).filter((x:any)=>x.type==='blob'&&String(x.path||'').startsWith(c.basePath)&&image(String(x.path||''))).map((x:any)=>{const p=String(x.path),f=p.split('/').pop()||p,e=p.split('/').map(encodeURIComponent).join('/');return{id:`github_${x.sha}`,provider:'github',githubOwner:c.githubOwner,githubRepository:c.githubRepository,branch:c.branch,path:p,filename:f,publicUrl:`https://raw.githubusercontent.com/${c.githubOwner}/${c.githubRepository}/${encodeURIComponent(c.branch)}/${e}`,mimeType:`image/${f.split('.').pop()}`,fileSize:0,width:0,height:0,sha:x.sha,createdAt:new Date().toISOString(),originalFilename:f,altText:'',title:f}})}
async function upload(b:any,c:Config){const filename=clean(b.filename).replace(/[^A-Za-z0-9._-]/g,'');if(!filename||filename.includes('..'))return fail('INVALID_FILENAME','github_upload','نام فایل نامعتبر است.');const content=clean(b.base64);if(!content)return fail('EMPTY_IMAGE','github_upload','محتوای تصویر خالی است.');const raw=content.replace(/^data:[^;]+;base64,/,'');const size=Math.floor(raw.length*3/4);if(size>MAX)return fail('IMAGE_SIZE_LIMIT','github_upload','حجم تصویر بیش از ۸ مگابایت است.',{sizeBytes:size,maxBytes:MAX});const p=safePath(`${c.basePath}${filename}`);if(!p||!p.startsWith(c.basePath))return fail('INVALID_MEDIA_PATH','github_upload','مسیر فایل نامعتبر است.');const ep=`/repos/${c.githubOwner}/${c.githubRepository}/contents/${p.split('/').map(encodeURIComponent).join('/')}`;const old=await gh(`${ep}?ref=${encodeURIComponent(c.branch)}`);let oldSha='';if(old.ok){oldSha=(await body(old))?.sha||'';if(!b.overwrite)return fail('FILE_EXISTS','github_upload',`فایلی با نام «${filename}» از قبل وجود دارد.`,{existingSha:oldSha})}else if(old.status!==404){const d=await body(old);return fail(old.status===403?'GITHUB_FILE_READ_FORBIDDEN':'GITHUB_EXISTING_FILE_ERROR','github_upload',`بررسی فایل موجود در GitHub ناموفق بود (${old.status}).`,{status:old.status,githubMessage:d?.message||null})}const put=await gh(ep,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Upload media asset: ${filename} via Solmint Admin`,content:raw,branch:c.branch,...(oldSha?{sha:oldSha}:{})})});const pd=await body(put);if(!put.ok){const code=put.status===403?'GITHUB_WRITE_FORBIDDEN':put.status===404?'GITHUB_CONTENT_PATH_NOT_FOUND':put.status===409?'GITHUB_UPDATE_CONFLICT':put.status===422?'GITHUB_UPLOAD_VALIDATION':'GITHUB_UPLOAD_FAILED';return fail(code,'github_upload',`آپلود تصویر در GitHub ناموفق بود (${put.status}).`,{status:put.status,githubMessage:pd?.message||null,documentationUrl:pd?.documentation_url||null})}return ok({asset:{id:`asset_${crypto.randomUUID()}`,provider:'github',githubOwner:c.githubOwner,githubRepository:c.githubRepository,branch:c.branch,path:p,filename,publicUrl:`https://raw.githubusercontent.com/${c.githubOwner}/${c.githubRepository}/${encodeURIComponent(c.branch)}/${p.split('/').map(encodeURIComponent).join('/')}`,mimeType:b.mimeType||'image/webp',fileSize:Number(b.sizeBytes||size),width:Number(b.width||0),height:Number(b.height||0),sha:pd?.content?.sha||oldSha,createdAt:new Date().toISOString(),originalFilename:b.originalFilename||filename,altText:String(b.altText||'').slice(0,500),title:String(b.title||filename).slice(0,255)},message:'تصویر با موفقیت در GitHub ذخیره شد.'})}
async function remove(b:any,c:Config){const p=safePath(b.path);if(!p||!p.startsWith(c.basePath))return fail('INVALID_MEDIA_PATH','github_delete','مسیر فایل برای این کتابخانه معتبر نیست.');const ep=`/repos/${c.githubOwner}/${c.githubRepository}/contents/${p.split('/').map(encodeURIComponent).join('/')}`;const r=await gh(`${ep}?ref=${encodeURIComponent(c.branch)}`);if(r.status===404)return ok({message:'فایل در GitHub وجود ندارد.'});if(!r.ok)return fail('GITHUB_DELETE_READ_FAILED','github_delete',`خواندن فایل برای حذف ناموفق بود (${r.status}).`,{status:r.status});const d=await body(r);const del=await gh(ep,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:`Delete media asset: ${p} via Solmint Admin`,sha:b.sha||d?.sha,branch:c.branch})});if(!del.ok){const dd=await body(del);return fail(del.status===403?'GITHUB_DELETE_FORBIDDEN':'GITHUB_DELETE_FAILED','github_delete',`حذف فایل از GitHub ناموفق بود (${del.status}).`,{status:del.status,githubMessage:dd?.message||null})}return ok({message:'تصویر با موفقیت از GitHub حذف شد.'})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return fail('METHOD_NOT_ALLOWED','request_validation','فقط POST مجاز است.',{},405);try{const a=await auth(req);if(!a.ok)return fail(a.code,a.stage,'احراز هویت مدیر برای سرویس رسانه ناموفق بود.');const b=await req.json().catch(()=>({}));const action=String(b.action||'');const c=b.config?cfg(b.config):await getConfig();if(action==='get-config')return ok({config:c,hasToken:Boolean(GH),authModel:'session-server-side'});if(action==='test'){const r=await preflight(c);if(r.status===200&&r.headers.get('content-type')?.includes('application/json')){const d=await new Response(r.body).clone().json().catch(()=>null);if(d?.success)await saveConfig({...c,connectionStatus:'connected'})}return r}if(action==='save-config'){const r=await preflight(c);const d=await new Response(r.body).clone().json().catch(()=>null);if(!d?.success)return r;await saveConfig({...c,connectionStatus:'connected'});return ok({config:{...c,connectionStatus:'connected'}})}if(action==='list')return ok({assets:await list(c),config:c});if(action==='upload')return upload(b,c);if(action==='delete')return remove(b,c);return fail('INVALID_ACTION','request_validation','عملیات رسانه نامعتبر است.')}catch(e){const message=e instanceof Error?e.message:String(e);console.error('github-media',message);return fail(message==='GITHUB_TOKEN_MISSING'?'GITHUB_TOKEN_MISSING':'MEDIA_RUNTIME_ERROR','server_runtime',message==='GITHUB_TOKEN_MISSING'?'توکن GitHub در Edge Function تنظیم نشده است.':'سرویس کتابخانه تصاویر در پردازش درخواست با خطا مواجه شد.',{runtimeError:message})}});