import React, { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, ChevronDown, Coins, Flame, KeyRound, Layers, Lock, Smartphone, Sparkles, WalletCards, Zap } from 'lucide-react';
import { Article, SolanaStatus } from '../../types';
import { fetchCmsSettingsFromApi } from '../../utils/cmsApiClient';

type Props = {
  articles: Article[];
  status: SolanaStatus;
  onNavigate: (path: string) => void;
};

const featureItems = [
  { title: 'Non-custodial Solana wallet', subtitle: 'User-controlled keys', icon: KeyRound, body: 'The wallet architecture keeps signing authority with the user and separates sensitive wallet operations from the public website.' },
  { title: 'SPL token creation', subtitle: 'No-code token workflow', icon: Layers, body: 'Create and manage Solana tokens with configurable supply, decimals, metadata and transaction review before signing.' },
  { title: 'Meme coin tools', subtitle: 'Solana meme coin creator', icon: Flame, body: 'Configure mint settings and token authorities while keeping the final transaction under the users control.' },
  { title: 'NFT minting', subtitle: 'Metaplex ecosystem', icon: Sparkles, body: 'A dedicated surface for creating and minting Solana digital assets with metadata-aware workflows.' },
  { title: 'Jupiter swap', subtitle: 'DEX aggregation', icon: Zap, body: 'Quote and execute token swaps through the existing Solana trading infrastructure and user-controlled signing flow.' },
  { title: 'Rent recovery', subtitle: 'Recover unused SOL', icon: Coins, body: 'Find eligible token accounts, close them and recover the SOL associated with rent when the account can safely be closed.' },
  { title: 'Batch transfers', subtitle: 'SOL and SPL operations', icon: WalletCards, body: 'Prepare grouped transfers and wallet operations for multiple recipients from the mobile workflow.' },
  { title: 'Liquidity tooling', subtitle: 'Raydium ecosystem', icon: Layers, body: 'The project is expanding its Solana liquidity tooling around pool creation and LP-related operations.' }
];

const securityItems = [
  ['Local key control', 'Sensitive wallet material is intended to stay on the device rather than being transmitted to the website.'],
  ['Server-authoritative APIs', 'Publishing, authentication and protected operations are validated on the server instead of trusting browser state.'],
  ['Transaction review', 'Transactions should be reviewed by the user before signing and broadcasting to Solana.'],
  ['Transparent architecture', 'The public repository makes the implementation and security direction inspectable.']
];

const roadmapItems = [
  ['Phase 1', 'Core non-custodial wallet', 'Wallet creation, recovery, SOL/SPL balances and on-device transaction signing.', 'completed'],
  ['Phase 2', 'DEX swap integration', 'Jupiter-based token swap infrastructure and transaction execution.', 'completed'],
  ['Phase 3', 'SPL & memecoin studio', 'Token creation, metadata, supply controls and authority-aware workflows.', 'completed'],
  ['Phase 4', 'Metaplex NFT minting', 'NFT creation and minting workflows for Solana digital assets.', 'completed'],
  ['Phase 5', 'Raydium liquidity tooling', 'Liquidity pool and LP-related operations are being expanded.', 'in_progress'],
  ['Phase 6', 'Broader device support', 'Future expansion of the Solmint experience beyond the current Android-first direction.', 'planned']
] as const;

const faqItems = [
  ['Is Solmint custodial?', 'No. The wallet direction is non-custodial: users control signing keys locally and the website is not intended to custody user assets.'],
  ['Does the website need my seed phrase or private key?', 'No. Sensitive wallet credentials should never be entered into the public website, support chats or unofficial forms.'],
  ['Can I create a Solana token without coding?', 'Yes. Solmint provides a guided token-creation workflow for core mint parameters and metadata.'],
  ['Can I create a Solana meme coin?', 'The application includes meme-coin creation tooling around token configuration and authority management.'],
  ['Can I mint NFTs on Solana?', 'Yes. The project includes a dedicated NFT minting direction using Solana ecosystem tooling.'],
  ['How does Swap work?', 'The existing application integrates Jupiter for quotes and swap transactions, which are then signed by the users wallet.'],
  ['What is Rent Recovery?', 'Eligible token accounts can sometimes be closed and the associated rent SOL recovered to the appropriate destination.'],
  ['Where are English articles managed?', 'The English surface uses the same publishing/data infrastructure while linking English and Persian articles through a translation group.']
];

const EnglishShowcase: React.FC = () => {
  const [config, setConfig] = useState<any>(null);
  const [index, setIndex] = useState(0);
  useEffect(() => { let cancelled = false; fetchCmsSettingsFromApi().then(settings => { const showcase = (settings as any)?.appShowcase; if (!cancelled && showcase) setConfig(showcase); }).catch(() => {}); return () => { cancelled = true; }; }, []);
  const slides = useMemo(() => (config?.slides || []).filter((s: any) => s?.enabled && s?.imageUrl).sort((a: any, b: any) => a.order - b.order), [config]);
  useEffect(() => { if (index >= slides.length) setIndex(0); }, [index, slides.length]);
  if (!config?.enabled || slides.length === 0) return null;
  const slide = slides[index];
  return <section className="relative overflow-hidden py-24 border-b border-white/5" aria-labelledby="english-showcase-title"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 grid lg:grid-cols-[1fr_.8fr] gap-14 items-center"><div className="space-y-6"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-bold text-[#14F195]"><Smartphone className="w-4 h-4" />Solmint Android app</div><h2 id="english-showcase-title" className="text-4xl sm:text-5xl font-black text-white leading-tight">See the wallet experience as it appears on mobile</h2><p className="max-w-xl text-slate-300 leading-8">The website introduces the product while the Android application handles the wallet experience and sensitive signing flow.</p><div className="flex flex-wrap gap-2">{slides.map((item: any, i: number) => <button key={item.id} type="button" onClick={() => setIndex(i)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${i === index ? 'border-[#14F195] bg-[#14F195] text-slate-950' : 'border-white/10 bg-white/5 text-slate-300'}`}>{item.title}</button>)}</div></div><div className="flex justify-center"><div className="relative w-[min(74vw,340px)] rounded-[3rem] bg-gradient-to-br from-slate-500 via-slate-950 to-slate-700 p-2 shadow-2xl"><div className="overflow-hidden rounded-[2.6rem] bg-black aspect-[1440/3120]"><img src={slide.imageUrl} alt={slide.altText || slide.title} width={config.screenWidth || 1440} height={config.screenHeight || 3120} className="h-full w-full object-fill" loading="lazy" decoding="async" /></div></div></div></div></section>;
};

const EnglishLiveMarket: React.FC<{ status: SolanaStatus }> = ({ status }) => <section className="border-b border-white/5 bg-white/[0.015] py-8"><div className="max-w-7xl mx-auto grid grid-cols-2 gap-3 px-4 sm:grid-cols-4 sm:px-6 lg:px-8"><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><span className="text-[11px] text-slate-500">SOL price</span><strong className="mt-1 block text-xl font-black text-white">${status.price ? status.price.toLocaleString('en-US', { maximumFractionDigits: 4 }) : '—'}</strong></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><span className="text-[11px] text-slate-500">24h change</span><strong className={`mt-1 block text-xl font-black ${status.change24h >= 0 ? 'text-[#14F195]' : 'text-rose-400'}`}>{status.price ? `${status.change24h >= 0 ? '+' : ''}${status.change24h.toFixed(2)}%` : '—'}</strong></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><span className="text-[11px] text-slate-500">Solana TPS</span><strong className="mt-1 block text-xl font-black text-white">{status.tps ? status.tps.toLocaleString('en-US') : '—'}</strong></div><div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><span className="text-[11px] text-slate-500">Average fee</span><strong className="mt-1 block text-xl font-black text-white">{status.avgFeeUsd ? `$${status.avgFeeUsd.toFixed(5)}` : '—'}</strong></div></div></section>;

export const EnglishHomeSections: React.FC<Props> = ({ articles, status, onNavigate }) => <>
  <EnglishLiveMarket status={status} />
  <EnglishShowcase />
  <section id="features" className="relative overflow-hidden border-b border-white/5 py-20"><div className="max-w-7xl mx-auto space-y-12 px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl space-y-4 text-center"><h2 className="text-4xl sm:text-5xl font-black text-white">Solmint capabilities <span className="bg-gradient-to-r from-[#9945FF] to-[#14F195] bg-clip-text text-transparent">at a glance</span></h2><p className="text-sm leading-7 text-slate-400">The English experience exposes the same major product direction as the Persian platform, with English content and navigation.</p></div><div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">{featureItems.map(({ title, subtitle, icon: Icon, body }) => <article key={title} className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 transition hover:border-[#14F195]/30"><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[#9945FF]/25 bg-[#9945FF]/10 text-[#14F195]"><Icon className="h-5 w-5" /></div><h3 className="mt-4 text-base font-black text-white">{title}</h3><div className="mt-1 text-[11px] font-bold text-[#14F195]">{subtitle}</div><p className="mt-3 text-xs leading-7 text-slate-400">{body}</p></article>)}</div></div></section>
  <section className="border-b border-white/5 py-20"><div className="max-w-7xl mx-auto space-y-12 px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl space-y-4 text-center"><h2 className="text-3xl sm:text-4xl font-black text-white">Security by design</h2><p className="text-sm leading-7 text-slate-400">The English surface follows the same security direction: minimize what the web layer can control and keep sensitive signing with the user.</p></div><div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">{securityItems.map(([title, body]) => <article key={title} className="rounded-2xl border border-white/10 bg-slate-950/60 p-6"><CheckCircle2 className="h-5 w-5 text-[#14F195]" /><h3 className="mt-4 text-base font-black text-white">{title}</h3><p className="mt-3 text-xs leading-7 text-slate-400">{body}</p></article>)}</div></div></section>
  <section className="border-b border-white/5 py-20"><div className="max-w-7xl mx-auto space-y-12 px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl space-y-4 text-center"><h2 className="text-3xl sm:text-4xl font-black text-white">Roadmap &amp; next steps</h2><p className="text-sm leading-7 text-slate-400">A transparent view of completed capabilities, current work and future expansion.</p></div><div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">{roadmapItems.map(([phase, title, body, state]) => <article key={phase} className={`rounded-2xl border p-6 ${state === 'completed' ? 'border-emerald-500/25 bg-emerald-500/[0.03]' : state === 'in_progress' ? 'border-[#9945FF]/40 bg-[#9945FF]/[0.04]' : 'border-white/10 bg-white/[0.02]'}`}><div className="flex items-center justify-between gap-3"><span className="font-mono text-xs font-bold text-slate-500">{phase}</span><span className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{state === 'completed' ? 'Completed' : state === 'in_progress' ? 'In progress' : 'Planned'}</span></div><h3 className="mt-4 text-base font-black text-white">{title}</h3><p className="mt-3 text-xs leading-7 text-slate-400">{body}</p></article>)}</div></div></section>
  <section className="border-b border-white/5 py-20"><div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl sm:text-4xl font-black text-white">Frequently asked questions</h2><p className="mt-3 text-sm leading-7 text-slate-400">The same product and security questions are answered in English for international readers.</p></div><div className="mt-10 space-y-3">{faqItems.map(([q, a]) => <details key={q} className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"><summary className="flex cursor-pointer items-center justify-between gap-4 text-sm font-bold text-white"><span>{q}</span><ChevronDown className="h-4 w-4 text-slate-500" /></summary><p className="pt-4 text-sm leading-7 text-slate-400">{a}</p></details>)}</div></div></section>
  <section className="border-b border-white/5 py-20"><div className="max-w-7xl mx-auto space-y-10 px-4 sm:px-6 lg:px-8"><div className="flex flex-col items-center justify-between gap-5 sm:flex-row"><div><h2 className="text-3xl sm:text-4xl font-black text-white">Latest English research</h2><p className="mt-2 text-sm text-slate-400">English articles use the same publication system and translation groups as the main site.</p></div><button type="button" onClick={() => onNavigate('/en/blog')} className="rounded-2xl border border-white/10 bg-white/5 px-5 py-3 text-xs font-bold text-white hover:border-[#14F195]/30">Open the English blog <ArrowRight className="ml-1 inline h-4 w-4 text-[#14F195]" /></button></div><div className="grid grid-cols-1 gap-5 md:grid-cols-3">{articles.slice(0, 3).map(article => <button key={article.id} type="button" onClick={() => onNavigate(`/en/articles/${encodeURIComponent(article.slug)}`)} className="group rounded-3xl border border-white/10 bg-[#101020]/80 p-5 text-left hover:border-[#9945FF]/50"><div className="text-[11px] text-slate-500">{article.category}</div><h3 className="mt-3 line-clamp-2 text-base font-black text-white group-hover:text-[#14F195]">{article.title}</h3><p className="mt-3 line-clamp-3 text-xs leading-7 text-slate-400">{article.summary}</p></button>)}</div>{articles.length === 0 && <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-8 text-center text-sm text-slate-500">English articles will appear here as they are published.</div>}</div></section>
  <section className="py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-3xl border border-[#9945FF]/20 bg-gradient-to-br from-[#9945FF]/10 to-[#14F195]/5 p-8 sm:p-10"><div className="grid gap-8 md:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-widest text-[#14F195]">Open source</p><h2 className="mt-2 text-2xl font-black text-white">The code is public.</h2></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#14F195]">One project</p><h2 className="mt-2 text-2xl font-black text-white">English and Persian use the same production system.</h2></div><div><p className="text-xs font-bold uppercase tracking-widest text-[#14F195]">No URL migration</p><h2 className="mt-2 text-2xl font-black text-white">Existing Persian paths stay where they are.</h2></div></div><a href="https://github.com/azad2022/solsite" target="_blank" rel="noreferrer" className="mt-8 inline-flex rounded-xl border border-white/10 bg-white/5 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">View the GitHub repository</a></div></div></section>
</>;
