import React, { useEffect } from 'react';
import { applyToolSeo } from '../../utils/toolsSeo';

interface Props { onNavigate: (path: string) => void; }
const tools = [
  { path: '/tools/solana-token-scanner', eyebrow: 'Token Scanner', title: 'بررسی توکن سولانا', description: 'اطلاعات فنی یک Mint را بررسی کنید؛ از عرضه و مجوزها تا برنامه توکن، متادیتا و توزیع حساب‌های بزرگ.', badge: 'تحلیل پایه' },
  { path: '/tools/token-2022-inspector', eyebrow: 'Token-2022 Inspector', title: 'بازرس Token-2022', description: 'قابلیت‌ها و Extensionهای Token-2022 را جداگانه بررسی کنید و بفهمید هر قابلیت چه اثری روی Mint دارد.', badge: 'تحلیل تخصصی' },
];

export const SolanaTokenToolsHub: React.FC<Props> = ({ onNavigate }) => {
  useEffect(() => { applyToolSeo({ title: 'ابزارهای بررسی توکن سولانا | سولمینت', description: 'ابزارهای تخصصی سولمینت برای بررسی فنی توکن‌های سولانا و Token-2022؛ فقط‌خواندنی، رایگان و بدون نیاز به اتصال کیف پول.', path: '/tools/solana-token-tools' }); }, []);
  return <section className="relative overflow-hidden py-16 sm:py-20">
    <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_20%_10%,rgba(153,69,255,.12),transparent_32%),radial-gradient(circle_at_85%_30%,rgba(20,241,149,.08),transparent_30%)]" />
    <div className="relative mx-auto max-w-6xl px-4 sm:px-6">
      <div className="max-w-3xl mb-10"><span className="inline-flex rounded-full border border-slate-700/70 bg-slate-900/70 px-3 py-1 text-xs font-bold text-slate-300">Solmint Tools</span><h1 className="mt-5 text-3xl sm:text-5xl font-black tracking-tight text-white">ابزارهای بررسی توکن سولانا</h1><p className="mt-4 text-sm sm:text-base leading-8 text-slate-400">دو ابزار تخصصی برای بررسی اطلاعات on-chain توکن‌های سولانا. این ابزارها فقط داده‌های عمومی شبکه را می‌خوانند و هیچ تراکنشی از طرف شما ارسال نمی‌کنند.</p></div>
      <div className="grid gap-5 lg:grid-cols-2">{tools.map(tool => <article key={tool.path} className="group rounded-3xl border border-slate-800/80 bg-slate-950/70 p-6 sm:p-8 shadow-[0_20px_70px_rgba(0,0,0,.22)] transition-transform duration-300 hover:-translate-y-1"><div className="flex items-center justify-between gap-4"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#14F195]">{tool.eyebrow}</span><span className="rounded-full border border-slate-700 px-2.5 py-1 text-[11px] font-bold text-slate-400">{tool.badge}</span></div><h2 className="mt-5 text-2xl font-black text-white">{tool.title}</h2><p className="mt-3 min-h-20 text-sm leading-7 text-slate-400">{tool.description}</p><button type="button" onClick={() => onNavigate(tool.path)} className="mt-6 inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3 text-sm font-extrabold text-white transition hover:border-[#14F195]/50 hover:text-[#14F195]">ورود به ابزار <span aria-hidden="true">←</span></button></article>)}</div>

      <div className="mt-10 rounded-3xl border border-slate-800/80 bg-slate-950/70 p-6 sm:p-8">
        <div className="max-w-3xl"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#14F195]">راهنمای استفاده</span><h2 className="mt-3 text-2xl sm:text-3xl font-black text-white">این ابزارها دقیقاً چه کاری انجام می‌دهند؟</h2><p className="mt-3 text-sm leading-8 text-slate-400">اگر با آدرس‌های سولانا و اصطلاحاتی مثل Mint، Authority و Token-2022 آشنا نیستید، قبل از تحلیل توکن این راهنما را بخوانید. هدف ابزارها تبدیل داده خام شبکه به اطلاعات قابل فهم است؛ نه صدور حکم قطعی درباره خوب یا بد بودن یک پروژه.</p></div>
        <div className="mt-8 grid gap-4 md:grid-cols-2">
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۱. از کجا شروع کنم؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">اگر فقط می‌خواهید بفهمید یک توکن چه وضعیتی دارد، از Token Scanner شروع کنید. آدرس Mint را از منبع قابل اعتماد پروژه یا Explorer کپی کنید و در کادر ابزار قرار دهید. نام یا نماد توکن برای شناسایی کافی نیست؛ تحلیل باید بر اساس Mint Address انجام شود.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۲. Mint Address چیست؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">Mint Address شناسه حساب Mint روی شبکه سولاناست. این آدرس مشخص می‌کند داده‌هایی که می‌بینید مربوط به کدام دارایی هستند. قبل از تحلیل، آدرس را با منبع رسمی پروژه یا یک Explorer معتبر تطبیق دهید؛ توکن‌های مختلف می‌توانند نام و Symbol یکسان داشته باشند.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۳. Authorityها را چطور بخوانم؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">Mint Authority می‌تواند در شرایط مجاز عرضه توکن را افزایش دهد. Freeze Authority می‌تواند قابلیت فریزکردن Token Accountها را در اختیار دارنده آن قرار دهد. «لغو شده» یعنی authority مربوطه در وضعیت on-chain قابل استفاده نیست؛ فعال بودن هم به‌تنهایی به معنی کلاهبرداری نیست و باید در کنار سایر داده‌ها تفسیر شود.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۴. Supply و Decimals چه معنایی دارند؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">Supply مقدار واحدهای توکن است و Decimals تعداد رقم اعشار نمایش‌پذیر را تعیین می‌کند. قیمت پایین هر واحد به‌تنهایی نشانه ارزان بودن دارایی نیست؛ برای تحلیل اقتصادی باید ارزش بازار، عرضه و نقدشوندگی را نیز در نظر گرفت.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۵. توزیع حساب‌های بزرگ چه چیزی را نشان می‌دهد؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">Scanner حساب‌های Token بزرگ را از RPC شبکه دریافت می‌کند. درصد Top 10 نشان‌دهنده سهم ده حساب بزرگ از Supply است، نه تعداد کل هولدرها. یک Token Account نیز الزاماً خودِ شخص یا نهاد نهایی نیست؛ بنابراین این داده شاخص تمرکز است، نه شناسایی قطعی مالکیت انسانی.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۶. Metadata چه کاربردی دارد؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">Metadata می‌تواند نام، Symbol، URI و اطلاعاتی درباره Update Authority را مشخص کند. وجود Metadata یا تصویر زیبا اثبات امنیت پروژه نیست. URI خارجی نیز لزوماً محتوای قابل اعتماد ندارد و باید مستقل بررسی شود.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۷. Token-2022 Inspector برای چه کسانی است؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">اگر Token Scanner تشخیص دهد Mint از Token-2022 استفاده می‌کند، Inspector برای بررسی Extensionها مناسب است. Extensionها قابلیت‌هایی مانند Transfer Fee، Transfer Hook، Permanent Delegate، Default Account State و قابلیت‌های دیگر را اضافه می‌کنند.</p></div>
          <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h3 className="text-base font-black text-white">۸. آیا این ابزار می‌گوید توکن امن است؟</h3><p className="mt-3 text-sm leading-7 text-slate-400">خیر. ابزار Solmint یک تحلیل فنی read-only است. از روی چند داده on-chain نمی‌توان امنیت قرارداد، اعتبار تیم، کیفیت نقدشوندگی یا احتمال سودآوری را تضمین کرد. نتیجه باید بخشی از فرایند تحقیق شما باشد، نه جایگزین آن.</p></div>
        </div>

        <div className="mt-8 rounded-2xl border border-violet-400/15 bg-violet-400/[0.04] p-5"><h3 className="text-base font-black text-white">فرآیند پیشنهادی برای بررسی یک توکن</h3><ol className="mt-4 space-y-3 text-sm leading-7 text-slate-400"><li><strong className="text-slate-200">۱)</strong> Mint Address را از منبع رسمی پروژه تطبیق دهید.</li><li><strong className="text-slate-200">۲)</strong> Token Scanner را اجرا کنید و Token Program، Supply و Authorityها را بررسی کنید.</li><li><strong className="text-slate-200">۳)</strong> تمرکز حساب‌های بزرگ را ببینید و آن را با ساختار توزیع پروژه تفسیر کنید.</li><li><strong className="text-slate-200">۴)</strong> Metadata و Update Authority را بررسی کنید؛ اطلاعات off-chain را به‌عنوان ادعای قابل تأیید در نظر بگیرید.</li><li><strong className="text-slate-200">۵)</strong> اگر Token-2022 است، Inspector را باز کنید و Extensionهای فعال و پارامترهایشان را بخوانید.</li><li><strong className="text-slate-200">۶)</strong> برای تصمیم سرمایه‌گذاری، نقدشوندگی، بازار، قراردادهای مرتبط، سابقه پروژه و منابع مستقل را جداگانه بررسی کنید.</li></ol></div>
      </div>

      <div className="mt-8 rounded-2xl border border-amber-500/15 bg-amber-500/[0.04] p-5 text-sm leading-7 text-slate-400"><strong className="text-slate-200">مرز ابزار:</strong> این ابزارها برای ارزیابی فنی و مشاهده داده‌های عمومی طراحی شده‌اند و به‌تنهایی امنیت، اعتبار پروژه یا ارزش سرمایه‌گذاری یک توکن را تضمین نمی‌کنند. هیچ‌یک از ابزارها Seed Phrase، Private Key یا امضای تراکنش درخواست نمی‌کنند.</div>
    </div>
  </section>;
};
