import React, { useEffect, useMemo, useState } from 'react';
import { applyToolSeo } from '../../utils/toolsSeo';

interface Props { onNavigate: (path: string) => void; }
interface DistributionAccount { rank: number; address: string; amount: string; uiAmount: string | number | null; percentageOfSupply: string; owner: string | null; delegate: string | null; state: string | null; }
interface RiskFlag { code: string; severity: 'info' | 'warning' | 'high'; title: string; detail: string; }
interface TokenMetadata { found: boolean; account: string | null; updateAuthority: string | null; name: string | null; symbol: string | null; uri: string | null; mutable: boolean | null; primarySaleHappened?: boolean | null; }
interface TokenResult {
  ok: boolean; mint: string; tokenProgram: string; owner: string; slot: number | null; decimals: number; supply: string;
  isInitialized: boolean; mintAuthority: string | null; freezeAuthority: string | null;
  extensions: Array<{ type: string; data?: unknown }>; metadata?: TokenMetadata; analyzedAt?: string;
  distribution?: { sampledAccounts: number; top10Percentage: number; source: string; accounts: DistributionAccount[] };
  riskProfile?: { flags: RiskFlag[]; disclaimer: string }; error?: string;
}
const BASE58 = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/;
const short = (value: string | null) => value ? `${value.slice(0, 8)}…${value.slice(-8)}` : 'لغو شده';
const formatSupply = (value: string, decimals: number) => { try { const raw = BigInt(value); const divisor = 10 ** decimals; const number = Number(raw) / divisor; return Number.isFinite(number) ? number.toLocaleString('en-US', { maximumFractionDigits: Math.min(decimals, 8) }) : value; } catch { return value; } };
const flagClass = (severity: RiskFlag['severity']) => severity === 'high' ? 'border-rose-500/30 bg-rose-500/5' : severity === 'warning' ? 'border-amber-500/30 bg-amber-500/5' : 'border-slate-700 bg-slate-900/60';

export const SolanaTokenScannerPage: React.FC<Props> = ({ onNavigate }) => {
  const [mint, setMint] = useState(''); const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false); const [result, setResult] = useState<TokenResult | null>(null); const [error, setError] = useState('');
  const valid = useMemo(() => BASE58.test(mint.trim()), [mint]);
  useEffect(() => { applyToolSeo({ title: 'بررسی توکن سولانا | Solana Token Scanner | سولمینت', description: 'بررسی فنی توکن‌های سولانا با داده مستقیم شبکه؛ Authority، Supply، Token Program، متادیتا، توزیع حساب‌های بزرگ و پروفایل فنی را بررسی کنید.', path: '/tools/solana-token-scanner' }); const queryMint = new URLSearchParams(window.location.search).get('mint'); if (queryMint && BASE58.test(queryMint)) { setMint(queryMint); void analyze(queryMint); } }, []);
  async function analyze(address: string) { setLoading(true); setError(''); setResult(null); try { const response = await fetch(`/api/tools/solana-token?mint=${encodeURIComponent(address)}`); const payload = await response.json() as TokenResult; if (!response.ok || !payload.ok) throw new Error(payload.error || 'دریافت اطلاعات ناموفق بود.'); setResult(payload); window.history.replaceState({}, '', `/tools/solana-token-scanner?mint=${encodeURIComponent(address)}`); } catch (err) { setError(err instanceof Error ? err.message : 'خطای نامشخص در دریافت اطلاعات.'); } finally { setLoading(false); } }
  const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (valid) void analyze(mint.trim()); };

  return <section className="relative py-12 sm:py-16"><div className="mx-auto max-w-6xl px-4 sm:px-6">
    <button type="button" onClick={() => onNavigate('/tools/solana-token-tools')} className="text-sm font-bold text-slate-400 hover:text-white">← ابزارهای توکن سولانا</button>
    <div className="mt-8 max-w-3xl"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#14F195]">Solana Token Scanner</span><h1 className="mt-4 text-3xl sm:text-5xl font-black tracking-tight text-white">بررسی توکن سولانا</h1><p className="mt-4 text-sm sm:text-base leading-8 text-slate-400">Mint Address را وارد کنید تا وضعیت واقعی Mint، Authorityها، متادیتای on-chain و توزیع حساب‌های بزرگ را مستقیماً از شبکه بررسی کنیم. این ابزار read-only است و هیچ تراکنشی امضا نمی‌کند.</p></div>
    <form onSubmit={submit} className="mt-8 rounded-3xl border border-slate-800 bg-slate-950/80 p-5 sm:p-7"><label htmlFor="token-mint" className="block text-sm font-bold text-slate-200">آدرس Mint توکن</label><div className="mt-3 flex flex-col gap-3 sm:flex-row"><input id="token-mint" value={mint} onChange={e => { setMint(e.target.value); setSubmitted(false); setError(''); setResult(null); }} dir="ltr" inputMode="text" autoComplete="off" placeholder="مثلاً 4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-slate-900 px-4 py-3.5 text-sm text-white outline-none transition focus:border-[#14F195]/60" /><button disabled={loading} type="submit" className="rounded-xl bg-[#14F195] px-6 py-3.5 text-sm font-black text-slate-950 transition hover:brightness-110 disabled:cursor-wait disabled:opacity-60">{loading ? 'در حال بررسی…' : 'بررسی توکن'}</button></div>{submitted && !valid && <p className="mt-3 text-xs font-bold text-rose-400">آدرس واردشده از نظر طول و قالب Base58 معتبر نیست.</p>}{error && <p role="alert" className="mt-3 text-sm font-bold text-rose-400">{error}</p>}</form>
    {result && <div className="mt-8 space-y-5">
      <div className="flex flex-col gap-2 rounded-2xl border border-[#14F195]/20 bg-[#14F195]/5 p-5 sm:flex-row sm:items-center sm:justify-between"><div><span className="text-xs font-bold text-[#14F195]">Mint معتبر و قابل خواندن</span><p dir="ltr" className="mt-2 break-all font-mono text-xs text-slate-300">{result.mint}</p></div><span className="rounded-full border border-slate-700 px-3 py-1 text-xs font-bold text-slate-300">{result.tokenProgram}</span></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Supply', formatSupply(result.supply, result.decimals)], ['Decimals', String(result.decimals)], ['Mint Authority', short(result.mintAuthority)], ['Freeze Authority', short(result.freezeAuthority)]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><p className="text-xs font-bold text-slate-500">{label}</p><p dir={label === 'Supply' ? 'ltr' : undefined} className="mt-3 break-all text-sm font-extrabold text-slate-100">{value}</p></div>)}</div>
      {result.metadata && <div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-black text-white">هویت و Metadata توکن</h2><p className="mt-1 text-xs text-slate-500">Metadata Account از برنامه رسمی Metaplex در شبکه خوانده شده است؛ محتوای URI خارجی عمداً در این مرحله اجرا یا دانلود نمی‌شود.</p></div><span className={`rounded-full border px-3 py-1 text-xs font-bold ${result.metadata.found ? 'border-[#14F195]/30 text-[#14F195]' : 'border-slate-700 text-slate-500'}`}>{result.metadata.found ? 'Metadata پیدا شد' : 'Metadata پیدا نشد'}</span></div>{result.metadata.found && <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Name</span><p className="mt-2 break-words text-sm font-bold text-slate-100">{result.metadata.name || '—'}</p></div><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Symbol</span><p className="mt-2 text-sm font-bold text-slate-100">{result.metadata.symbol || '—'}</p></div><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Update Authority</span><p dir="ltr" className="mt-2 break-all font-mono text-xs text-slate-300">{result.metadata.updateAuthority ? short(result.metadata.updateAuthority) : '—'}</p></div><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Mutable</span><p className="mt-2 text-sm font-bold text-slate-100">{result.metadata.mutable === null ? 'نامشخص' : result.metadata.mutable ? 'بله' : 'خیر'}</p></div></div>}{result.metadata.uri && <div className="mt-4 rounded-xl border border-slate-800 bg-slate-900/50 p-4"><span className="text-xs text-slate-500">Metadata URI</span><p dir="ltr" className="mt-2 break-all font-mono text-xs leading-6 text-slate-300">{result.metadata.uri}</p></div>}</div>}
      {result.riskProfile && <div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><div className="flex items-center justify-between gap-4"><h2 className="text-base font-black text-white">پروفایل فنی توکن</h2><span className="text-xs text-slate-500">بر پایه داده on-chain</span></div><div className="mt-4 grid gap-3 md:grid-cols-2">{result.riskProfile.flags.map(flag => <div key={flag.code} className={`rounded-xl border p-4 ${flagClass(flag.severity)}`}><div className="flex items-start justify-between gap-3"><span className="text-sm font-black text-slate-100">{flag.title}</span><span className="text-[10px] font-bold uppercase text-slate-500">{flag.severity}</span></div><p className="mt-2 text-xs leading-6 text-slate-400">{flag.detail}</p></div>)}</div><p className="mt-4 text-xs leading-6 text-slate-500">{result.riskProfile.disclaimer}</p></div>}
      {result.distribution && <div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-base font-black text-white">توزیع حساب‌های بزرگ</h2><p className="mt-1 text-xs leading-6 text-slate-500">RPC شبکه ۲۰ Token Account بزرگ را برمی‌گرداند؛ درصد زیر سهم ۱۰ حساب اول از کل Supply است، نه تعداد کل هولدرها.</p></div><div className="text-left" dir="ltr"><span className="text-xs text-slate-500">Top 10</span><strong className="mt-1 block text-xl font-black text-white">{result.distribution.top10Percentage.toFixed(2)}%</strong></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs" dir="ltr"><thead className="border-b border-slate-800 text-slate-500"><tr><th className="px-3 py-3">#</th><th className="px-3 py-3">Token Account</th><th className="px-3 py-3">Owner</th><th className="px-3 py-3">Balance</th><th className="px-3 py-3">Supply %</th><th className="px-3 py-3">State</th></tr></thead><tbody>{result.distribution.accounts.map(account => <tr key={account.address} className="border-b border-slate-900"><td className="px-3 py-3 text-slate-500">{account.rank}</td><td className="px-3 py-3 font-mono text-slate-300">{short(account.address)}</td><td className="px-3 py-3 font-mono text-slate-400">{account.owner ? short(account.owner) : '—'}</td><td className="px-3 py-3 text-slate-200">{account.uiAmount ?? account.amount}</td><td className="px-3 py-3 font-bold text-slate-200">{account.percentageOfSupply}%</td><td className="px-3 py-3 text-slate-500">{account.state ?? '—'}</td></tr>)}</tbody></table></div></div>}
      <div className="rounded-2xl border border-slate-800 bg-slate-950/70 p-5"><div className="flex items-center justify-between gap-4"><h2 className="text-base font-black text-white">وضعیت پایه Mint</h2><span className="text-xs text-slate-500">Slot {result.slot ?? '—'}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Mint Authority</span><p className="mt-2 text-sm font-bold text-slate-200">{result.mintAuthority ? 'فعال' : 'لغو شده'}</p></div><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Freeze Authority</span><p className="mt-2 text-sm font-bold text-slate-200">{result.freezeAuthority ? 'فعال' : 'لغو شده'}</p></div><div className="rounded-xl bg-slate-900 p-4"><span className="text-xs text-slate-500">Initialized</span><p className="mt-2 text-sm font-bold text-slate-200">{result.isInitialized ? 'بله' : 'خیر'}</p></div></div></div>
      {result.tokenProgram === 'Token-2022' && <div className="rounded-2xl border border-[#9945FF]/30 bg-[#9945FF]/5 p-5"><h2 className="text-base font-black text-white">این توکن از Token-2022 استفاده می‌کند</h2><p className="mt-2 text-sm leading-7 text-slate-400">برای مشاهده جزئیات Extensionها، ابزار تخصصی Token-2022 Inspector را باز کنید.</p><button type="button" onClick={() => onNavigate(`/tools/token-2022-inspector?mint=${encodeURIComponent(result.mint)}`)} className="mt-4 rounded-xl border border-[#9945FF]/40 px-4 py-2 text-sm font-bold text-white hover:bg-[#9945FF]/10">باز کردن Token-2022 Inspector</button></div>}
    </div>}
    <div className="mt-8 rounded-2xl border border-slate-800 bg-slate-950/40 p-5 text-sm leading-7 text-slate-400"><strong className="text-slate-200">مرز ابزار:</strong> این صفحه فقط تحلیل فنی on-chain ارائه می‌کند. Authority، تمرکز حساب‌ها و Metadata به‌تنهایی امنیت، مشروعیت یا ارزش سرمایه‌گذاری یک پروژه را تضمین نمی‌کنند. محتوای URI خارجی و نقدشوندگی باید جداگانه و با کنترل‌های مناسب بررسی شوند.</div>
  </div></section>;
};
