import React, { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, Pause, Play, RefreshCw, Radio, Waves } from 'lucide-react';
import { fetchMemeTickerFeed, MemeTickerFeed, MemeTickerItem } from '../utils/memeTickerService';

const FALLBACK: MemeTickerFeed = { enabled: false, items: [] };
const usd = (v: number | null) => { if (v == null || !Number.isFinite(v)) return '—'; if (v >= 1000) return `$${v.toLocaleString('en-US', { maximumFractionDigits: 0 })}`; if (v >= 1) return `$${v.toLocaleString('en-US', { maximumFractionDigits: 2 })}`; if (v >= .01) return `$${v.toLocaleString('en-US', { minimumFractionDigits: 4, maximumFractionDigits: 6 })}`; return `$${v.toLocaleString('en-US', { minimumFractionDigits: 6, maximumFractionDigits: 10 })}`; };
const time = (v?: string) => { if (!v) return '—'; try { return new Date(v).toLocaleTimeString('fa-IR', { hour: '2-digit', minute: '2-digit', second: '2-digit' }); } catch { return '—'; } };
const source = (i: MemeTickerItem) => i.source === 'jupiter' ? 'Solana DEX' : i.pair || 'Spot';

const Logo: React.FC<{ item: MemeTickerItem; big?: boolean }> = ({ item, big }) => item.logoUrl ? <img src={item.logoUrl} alt="" className={`${big ? 'h-11 w-11' : 'h-8 w-8'} rounded-full object-cover ring-1 ring-slate-200`} loading="lazy" /> : <span className={`${big ? 'h-11 w-11' : 'h-8 w-8'} grid place-items-center rounded-full bg-gradient-to-br from-[#9945FF] to-[#14F195] text-[10px] font-black text-slate-950`}>{item.symbol.slice(0, 4)}</span>;
const Change: React.FC<{ value: number | null }> = ({ value }) => { if (value == null || !Number.isFinite(value)) return <span className="text-slate-400">—</span>; const up = value >= 0; return <span className={`inline-flex items-center gap-0.5 font-mono text-xs font-bold ${up ? 'text-emerald-600' : 'text-rose-600'}`}>{up ? <ArrowUpRight className="h-3.5 w-3.5" /> : <ArrowDownRight className="h-3.5 w-3.5" />}{up ? '+' : ''}{value.toFixed(2)}%</span>; };

const Featured: React.FC<{ item: MemeTickerItem }> = ({ item }) => <article className="group border-l border-slate-200 first:border-l-0 px-4 py-2.5"><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-2.5"><Logo item={item} big /><div className="min-w-0"><div className="flex items-center gap-2"><strong className="text-sm font-black text-slate-950">{item.symbol}</strong><span className="truncate text-[9px] uppercase tracking-widest text-slate-400">{source(item)}</span></div><div className="mt-1 truncate text-[10px] text-slate-500">{item.name}</div></div></div><div className="text-left" dir="ltr"><div className="font-mono text-lg font-black tracking-tight text-slate-950">{usd(item.priceUsd)}</div><Change value={item.change24h} /></div></div></article>;

const Row: React.FC<{ item: MemeTickerItem; rank: number }> = ({ item, rank }) => <div className="grid grid-cols-[28px_minmax(145px,1.5fr)_minmax(105px,1fr)_90px_90px] items-center gap-3 rounded-lg px-3 py-3 transition-colors hover:bg-slate-50" dir="ltr"><span className="text-center font-mono text-[10px] text-slate-400">{String(rank).padStart(2, '0')}</span><div className="flex min-w-0 items-center gap-2.5"><Logo item={item} /><div className="min-w-0"><div className="flex items-center gap-2"><strong className="text-xs font-black text-slate-900">{item.symbol}</strong><span className="hidden sm:block text-[9px] uppercase tracking-widest text-slate-400">{source(item)}</span></div><div className="truncate text-[10px] text-slate-500">{item.name}</div></div></div><div className="text-right font-mono text-sm font-bold text-slate-900">{usd(item.priceUsd)}</div><div className="text-right"><Change value={item.change24h} /></div><div className="text-right text-[9px] uppercase tracking-widest text-slate-400">USD</div></div>;

export const MemeTicker: React.FC = () => {
 const [feed,setFeed]=useState<MemeTickerFeed>(FALLBACK),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[reduced,setReduced]=useState(false),[loading,setLoading]=useState(true);
 const load=async()=>{try{setFeed(await fetchMemeTickerFeed())}catch{setFeed(x=>x.items.length?{...x,stale:true}:FALLBACK)}finally{setLoading(false)}};
 useEffect(()=>{load();const id=window.setInterval(load,Math.max(10000,(feed.refreshSeconds||20)*1000));return()=>window.clearInterval(id)},[feed.refreshSeconds]);
 useEffect(()=>{const m=window.matchMedia('(prefers-reduced-motion: reduce)');const f=()=>setReduced(m.matches);f();m.addEventListener?.('change',f);return()=>m.removeEventListener?.('change',f)},[]);
 const items=useMemo(()=>feed.items.filter(i=>i.enabled&&i.priceUsd!==null).sort((a,b)=>a.order-b.order),[feed.items]); const featured=items.slice(0,3); const sources=new Set(items.map(i=>i.source||'unknown')).size; const rising=items.filter(i=>(i.change24h??0)>=0).length;
 if(loading||!feed.enabled||!items.length)return null; const pausedNow=paused||hover||reduced;
 return <section className="border-y border-slate-200 bg-[#f5f7fa]" aria-label="بازار لحظه‌ای ارزهای دیجیتال"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:py-10" dir="rtl"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_18px_55px_rgba(15,23,42,.07)]">
  <header className="border-b border-slate-200 px-5 py-5 sm:px-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-950 text-white"><Activity className="h-4.5 w-4.5" /></div><div><div className="flex items-center gap-2"><h2 className="text-lg font-black tracking-tight text-slate-950 sm:text-xl">بازار لحظه‌ای</h2><span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black uppercase tracking-widest text-emerald-700"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Live</span></div><p className="mt-1 text-xs text-slate-500">قیمت‌ها و تغییرات لحظه‌ای بازارهای منتخب Solmint</p></div></div><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold text-slate-500"><span className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">{items.length} بازار</span><span className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">{sources} منبع</span><span className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">{rising} صعودی</span><span className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2">بروزرسانی {time(feed.fetchedAt)}</span></div></div></header>
  <div className="grid divide-y border-b border-slate-200 md:grid-cols-3 md:divide-x md:divide-y-0" dir="ltr">{featured.map(i=><Featured key={i.id} item={i}/>)}</div>
  <div className="p-3 sm:p-5"><div className="overflow-hidden rounded-xl border border-slate-200"><div className="flex items-center justify-between border-b border-slate-200 bg-slate-50 px-4 py-3" dir="rtl"><div><strong className="text-sm font-black text-slate-900">بازارهای منتخب</strong><span className="mr-2 text-[9px] uppercase tracking-widest text-slate-400">Live Spot Markets</span></div><div className="flex items-center gap-3 text-[10px] text-slate-400"><span>{feed.stale?'داده قدیمی':'داده زنده'}</span><button onClick={()=>setPaused(v=>!v)} className="grid h-7 w-7 place-items-center rounded-md border border-slate-200 bg-white hover:bg-slate-100" aria-label={paused?'ادامه':'توقف'}>{paused?<Play className="h-3 w-3"/>:<Pause className="h-3 w-3"/>}</button></div></div><div className="hidden grid-cols-[28px_minmax(145px,1.5fr)_minmax(105px,1fr)_90px_90px] gap-3 border-b border-slate-100 px-3 py-2 text-[9px] uppercase tracking-widest text-slate-400 md:grid" dir="ltr"><span>#</span><span>Asset</span><span className="text-right">Price</span><span className="text-right">24H</span><span className="text-right">Quote</span></div><div className="p-1.5 sm:p-2">{items.map((i,n)=><Row key={i.id} item={i} rank={n+1}/>)}</div></div></div>
  <div className="border-t border-slate-200 bg-slate-50/80" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)}><div className="flex items-center justify-between px-4 py-2 text-[9px] uppercase tracking-widest text-slate-400"><span>Market Tape</span><span>Public Data</span></div><div className="relative overflow-hidden border-t border-slate-200 py-2"><div className="flex w-max gap-2" style={{animation:`solmintTape ${Math.max(18,feed.speedSeconds||32)}s linear infinite`,animationPlayState:pausedNow?'paused':'running'}}>{[...items,...items].map((i,n)=><span key={`${i.id}-${n}`} className="inline-flex items-center gap-2 rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] shadow-sm" dir="ltr"><b>{i.symbol}</b><span className="font-mono text-slate-500">{usd(i.priceUsd)}</span><Change value={i.change24h}/></span>)}</div></div></div>
  <footer className="flex items-center justify-between px-5 py-3 text-[9px] text-slate-400"><span className="inline-flex items-center gap-1.5"><RefreshCw className="h-3 w-3"/>داده‌ها از منابع عمومی بازار دریافت می‌شوند.</span><span className="hidden sm:block">Solmint Market Data</span></footer>
 </div></div><style>{'@keyframes solmintTape{from{transform:translateX(0)}to{transform:translateX(-50%)}}'}</style></section>;
};