import type { PayLocale } from './types';

const labels = {
  'fa-IR': {
    merchant: 'مرچنت', amount: 'مبلغ', customerTotal: 'مبلغ نهایی مشتری', merchantSettlement: 'دریافتی مرچنت', fee: 'کارمزد درگاه', feePayer: 'پرداخت‌کننده کارمزد', customer: 'مشتری', asset: 'دارایی', network: 'شبکه', destination: 'مقصد', reference: 'مرجع', intentStatus: 'وضعیت پرداخت', commitment: 'تعهد تأیید',
    verificationSubmitted: 'درخواست بررسی ثبت شد. پرداخت تا اعلام وضعیت معتبر از سرویس پرداخت، موفق محسوب نمی‌شود.',
    notDetected: 'تراکنش مرتبط هنوز در بررسی خودکار پیدا نشده است.',
    loadFailed: 'دریافت درخواست پرداخت از سرویس پرداخت ناموفق بود.', expired: 'این درخواست پرداخت منقضی شده است.',
    payInstructions: 'کیف پول را متصل و پرداخت را تأیید کنید. پس از امضای تراکنش، سرویس پرداخت SolMint آن را به‌صورت خودکار بررسی می‌کند.',
    walletConnect: 'وضعیت کیف پول', walletGeneric: 'کیف پول', walletConnected: 'کیف پول متصل است', walletRequired: 'برای پرداخت با کیف پول آماده شوید.', walletDetected: 'کیف پول شناسایی شد', walletNotDetected: 'کیف پول داخل مرورگر شناسایی نشد', walletConnectionFailed: 'اتصال کیف پول انجام نشد. دوباره تلاش کنید.', walletSignatureMissing: 'کیف پول امضای تراکنش را برنگرداند. دوباره تلاش کنید.',
    copy: 'کپی', copied: 'کپی شد', connect: 'اتصال', changeWallet: 'تغییر کیف پول', disconnect: 'قطع اتصال', chooseWallet: 'انتخاب کیف پول', walletOptionsHint: 'یکی از کیف پول‌های شناسایی‌شده را انتخاب کنید.', technicalDetails: 'جزئیات فنی پرداخت', checkoutSnapshotDescription: 'جزئیات زیر از Payment Intent دریافت شده‌اند و برای بررسی و تطبیق نمایش داده می‌شوند.',
    walletHandoffTitle: 'کیف پول داخل مرورگر شناسایی نشد', walletHandoffDescription: 'می‌توانید این صفحه را داخل کیف پول موبایلی باز کنید یا آدرس عمومی کیف پول خود را وارد کنید.',
    walletAddressLabel: 'آدرس کیف پول مشتری', walletAddressPlaceholder: 'آدرس عمومی کیف پول را وارد کنید', walletAddressHint: 'این فقط آدرس عمومی است؛ انتقال وجه فقط پس از تأیید خود کیف پول انجام می‌شود.', walletAddressInvalid: 'آدرس کیف پول معتبر نیست.', walletAccountMismatch: 'کیف پول بازشده با آدرس واردشده یکسان نیست. کیف پول درست را باز کنید.',
    openInPhantom: 'باز کردن در Phantom', openInSolflare: 'باز کردن در Solflare', openInBackpack: 'باز کردن در Backpack', openCompatibleWallet: 'ادامه با کیف پول سازگار', copyWalletRequest: 'کپی درخواست کیف پول', walletRequestCopied: 'درخواست کپی شد', walletReturnHint: 'پس از تأیید در کیف پول، به همین صفحه برگردید. وضعیت پرداخت به‌صورت خودکار بررسی می‌شود.',
    verificationFailed: 'بررسی تراکنش کامل نشد. دوباره تلاش کنید.', receiptUnavailable: 'رسید در حال آماده‌سازی است. دوباره بررسی می‌شود.', payWithWallet: 'پرداخت با کیف پول', preparingPayment: 'در حال آماده‌سازی پرداخت...', openingWallet: 'در حال باز کردن کیف پول...', walletPaymentFailed: 'پرداخت با کیف پول انجام نشد. دوباره تلاش کنید.', walletTokenAccountMissing: 'کیف پول شما حساب توکن لازم را ندارد.', paymentConfirmed: 'پرداخت توسط سرویس پرداخت تأیید شد.', paymentCompleted: 'پرداخت با وضعیت نهایی تکمیل شد.', paymentUnderpaid: 'پرداخت کمتر از مبلغ موردنیاز شناسایی شد.', paymentOverpaid: 'پرداخت بیشتر از مبلغ موردنیاز شناسایی شد.', paymentAmbiguous: 'چند مشاهده سازگار شناسایی شد و بررسی نیاز به اقدام بعدی دارد.',
    intentLookupTitle: 'بررسی درخواست پرداخت', intentLookupDescription: 'شناسه درخواست پرداخت را وارد کنید تا تصویر رسمی پرداخت دریافت و بررسی شود.', intentLookupLabel: 'شناسه درخواست پرداخت', intentLookupPlaceholder: 'شناسه یکتای درخواست پرداخت را وارد کنید', checkIntent: 'بررسی Intent', invalidIntentId: 'شناسه درخواست پرداخت نامعتبر است.'

  'en-US': {
    merchant: 'Merchant', amount: 'Amount', customerTotal: 'Customer total', merchantSettlement: 'Merchant receives', fee: 'Gateway fee', feePayer: 'Fee payer', customer: 'Customer', asset: 'Asset', network: 'Network', destination: 'Destination', reference: 'Reference', intentStatus: 'Intent status', commitment: 'Verification commitment',
    verificationSubmitted: 'Verification was requested. The payment is not considered successful until the payment service reports an authoritative state.',
    notDetected: 'The related transaction has not been detected yet.',
    loadFailed: 'The Payment Intent could not be retrieved from the payment service.', expired: 'This Payment Intent has expired.',
    payInstructions: 'Connect your wallet and approve the payment. After the transaction is signed, SolMint Pay verifies the transaction automatically.',
    walletConnect: 'Wallet status', walletGeneric: 'Wallet', walletConnected: 'Wallet connected', walletRequired: 'Get your wallet ready to pay.', walletDetected: 'Wallet detected', walletNotDetected: 'No wallet was detected in this browser', walletConnectionFailed: 'Wallet connection failed. Try again.', walletSignatureMissing: 'The wallet did not return a transaction signature. Try again.',
    copy: 'Copy', copied: 'Copied', connect: 'Connect', changeWallet: 'Change wallet', disconnect: 'Disconnect', chooseWallet: 'Choose a wallet', walletOptionsHint: 'Select one of the detected wallets.', technicalDetails: 'Payment details', checkoutSnapshotDescription: 'These values come from the Payment Intent and are shown for inspection and reconciliation.',
    walletHandoffTitle: 'No wallet was detected in this browser', walletHandoffDescription: 'Open this checkout inside a mobile wallet or enter your public wallet address.',
    walletAddressLabel: 'Customer wallet address', walletAddressPlaceholder: 'Enter the public wallet address', walletAddressHint: 'This is a public address only. Funds move only after the wallet itself approves the transaction.', walletAddressInvalid: 'The wallet address is invalid.', walletAccountMismatch: 'The opened wallet does not match the entered address. Open the matching wallet.',
    openInPhantom: 'Open in Phantom', openInSolflare: 'Open in Solflare', openInBackpack: 'Open in Backpack', openCompatibleWallet: 'Continue with a compatible wallet', copyWalletRequest: 'Copy wallet request', walletRequestCopied: 'Request copied', walletReturnHint: 'After approving in your wallet, return to this page. Payment status is checked automatically.',
    verificationFailed: 'The transaction could not be verified. Try again.', receiptUnavailable: 'The receipt is still being prepared. We will check again.', payWithWallet: 'Pay with wallet', preparingPayment: 'Preparing payment...', openingWallet: 'Opening wallet...', walletPaymentFailed: 'Wallet payment could not be completed. Try again.', walletTokenAccountMissing: 'Your wallet does not have the required token account.', paymentConfirmed: 'The payment was confirmed by the payment service.', paymentCompleted: 'The payment reached the final completed state.', paymentUnderpaid: 'A payment below the required amount was detected.', paymentOverpaid: 'A payment above the required amount was detected.', paymentAmbiguous: 'Multiple compatible observations were found and the payment requires further resolution.',
    intentLookupTitle: 'Check Payment Intent', intentLookupDescription: 'Enter a Payment Intent ID to load and inspect the authoritative payment snapshot.', intentLookupLabel: 'Payment Intent ID', intentLookupPlaceholder: 'Enter the Payment Intent UUID', checkIntent: 'Check Intent', invalidIntentId: 'The Payment Intent ID is invalid.'

  ar: {
    merchant: 'التاجر', amount: 'المبلغ', customerTotal: 'إجمالي العميل', merchantSettlement: 'ما يستلمه التاجر', fee: 'رسوم البوابة', feePayer: 'دافع الرسوم', customer: 'العميل', asset: 'الأصل', network: 'الشبكة', destination: 'الوجهة', reference: 'المرجع', intentStatus: 'حالة الدفع', commitment: 'التزام التحقق',
    verificationSubmitted: 'تم طلب التحقق. لن يعتبر الدفع ناجحاً حتى تعلن خدمة الدفع حالة موثوقة.',
    notDetected: 'لم يتم اكتشاف المعاملة المرتبطة بعد.',
    loadFailed: 'تعذر جلب طلب الدفع من خدمة الدفع.', expired: 'انتهت صلاحية طلب الدفع هذا.',
    payInstructions: 'صِل محفظتك وأكّد الدفع. بعد توقيع المعاملة، تتحقق خدمة الدفع من المعاملة تلقائياً.',
    walletConnect: 'حالة المحفظة', walletGeneric: 'المحفظة', walletConnected: 'المحفظة متصلة', walletRequired: 'جهّز محفظتك للدفع.', walletDetected: 'تم اكتشاف المحفظة', walletNotDetected: 'لم يتم اكتشاف محفظة في هذا المتصفح', walletConnectionFailed: 'تعذر اتصال المحفظة. حاول مرة أخرى.', walletSignatureMissing: 'لم تُعد المحفظة توقيع المعاملة. حاول مرة أخرى.',
    copy: 'نسخ', copied: 'تم النسخ', connect: 'اتصال', changeWallet: 'تغيير المحفظة', disconnect: 'قطع الاتصال', chooseWallet: 'اختيار المحفظة', walletOptionsHint: 'اختر إحدى المحافظ التي تم اكتشافها.', technicalDetails: 'تفاصيل الدفع', checkoutSnapshotDescription: 'تأتي هذه القيم من Payment Intent وتُعرض للفحص والمطابقة.',
    walletHandoffTitle: 'لم يتم اكتشاف محفظة في هذا المتصفح', walletHandoffDescription: 'افتح صفحة الدفع داخل محفظة محمولة أو أدخل عنوان محفظتك العام.',
    walletAddressLabel: 'عنوان محفظة العميل', walletAddressPlaceholder: 'أدخل عنوان المحفظة العام', walletAddressHint: 'هذا عنوان عام فقط. لا يمكن نقل الأموال إلا بعد موافقة المحفظة نفسها على المعاملة.', walletAddressInvalid: 'عنوان المحفظة غير صالح.', walletAccountMismatch: 'المحفظة المفتوحة لا تطابق العنوان المدخل. افتح المحفظة المطابقة.',
    openInPhantom: 'فتح في Phantom', openInSolflare: 'فتح في Solflare', openInBackpack: 'فتح في Backpack', openCompatibleWallet: 'المتابعة بمحفظة متوافقة', copyWalletRequest: 'نسخ طلب المحفظة', walletRequestCopied: 'تم نسخ الطلب', walletReturnHint: 'بعد الموافقة في المحفظة، عد إلى هذه الصفحة. ستتم مراجعة حالة الدفع تلقائياً.',
    verificationFailed: 'تعذر التحقق من المعاملة. حاول مرة أخرى.', receiptUnavailable: 'يتم تجهيز الإيصال. ستتم إعادة المحاولة تلقائياً.', payWithWallet: 'الدفع بالمحفظة', preparingPayment: 'جارٍ تجهيز الدفع...', openingWallet: 'جارٍ فتح المحفظة...', walletPaymentFailed: 'تعذر إكمال الدفع بالمحفظة. حاول مرة أخرى.', walletTokenAccountMissing: 'لا تحتوي محفظتك على حساب الرمز المطلوب.', paymentConfirmed: 'تم تأكيد الدفع بواسطة خدمة الدفع.', paymentCompleted: 'اكتملت عملية الدفع بحالة نهائية.', paymentUnderpaid: 'تم اكتشاف دفع أقل من المبلغ المطلوب.', paymentOverpaid: 'تم اكتشاف دفع أكبر من المبلغ المطلوب.', paymentAmbiguous: 'تم العثور على ملاحظات متوافقة متعددة ويحتاج الدفع إلى معالجة إضافية.',
    intentLookupTitle: 'التحقق من طلب الدفع', intentLookupDescription: 'أدخل معرّف طلب الدفع لتحميل البيانات الرسمية للدفع وفحصها.', intentLookupLabel: 'معرّف طلب الدفع', intentLookupPlaceholder: 'أدخل المعرّف الفريد لطلب الدفع', checkIntent: 'تحقق من الطلب', invalidIntentId: 'معرّف طلب الدفع غير صالح.'

  ru: {
    merchant: 'Мерчант', amount: 'Сумма', customerTotal: 'Итого клиента', merchantSettlement: 'Получит мерчант', fee: 'Комиссия шлюза', feePayer: 'Плательщик комиссии', customer: 'Клиент', asset: 'Актив', network: 'Сеть', destination: 'Получатель', reference: 'Reference', intentStatus: 'Статус платежа', commitment: 'Требование проверки',
    verificationSubmitted: 'Запущена проверка. Платёж не считается успешным, пока платёжный сервис не сообщит достоверный статус.',
    notDetected: 'Связанная транзакция пока не обнаружена.',
    loadFailed: 'Не удалось получить запрос на оплату из платёжного сервиса.', expired: 'Срок действия этого запроса на оплату истёк.',
    payInstructions: 'Подключите кошелёк и подтвердите оплату. После подписи транзакции платёжный сервис автоматически проверит транзакцию.',
    walletConnect: 'Состояние кошелька', walletGeneric: 'Кошелёк', walletConnected: 'Кошелёк подключён', walletRequired: 'Подготовьте кошелёк к оплате.', walletDetected: 'Кошелёк обнаружен', walletNotDetected: 'В этом браузере кошелёк не обнаружен', walletConnectionFailed: 'Не удалось подключить кошелёк. Повторите попытку.', walletSignatureMissing: 'Кошелёк не вернул подпись транзакции. Повторите попытку.',
    copy: 'Копировать', copied: 'Скопировано', connect: 'Подключить', changeWallet: 'Сменить кошелёк', disconnect: 'Отключить', chooseWallet: 'Выберите кошелёк', walletOptionsHint: 'Выберите один из обнаруженных кошельков.', technicalDetails: 'Детали платежа', checkoutSnapshotDescription: 'Эти значения получены из запроса на оплату и показаны для проверки и сверки.',
    walletHandoffTitle: 'В этом браузере кошелёк не обнаружен', walletHandoffDescription: 'Откройте эту страницу оплаты внутри мобильного кошелька или введите публичный адрес кошелька.',
    walletAddressLabel: 'Адрес кошелька клиента', walletAddressPlaceholder: 'Введите публичный адрес кошелька', walletAddressHint: 'Это только публичный адрес. Средства переводятся только после подтверждения транзакции самим кошельком.', walletAddressInvalid: 'Адрес кошелька недействителен.', walletAccountMismatch: 'Открытый кошелёк не соответствует введённому адресу. Откройте соответствующий кошелёк.',
    openInPhantom: 'Открыть в Phantom', openInSolflare: 'Открыть в Solflare', openInBackpack: 'Открыть в Backpack', openCompatibleWallet: 'Продолжить с совместимым кошельком', copyWalletRequest: 'Скопировать запрос кошелька', walletRequestCopied: 'Запрос скопирован', walletReturnHint: 'После подтверждения в кошельке вернитесь на эту страницу. Сервис автоматически проверит статус платежа.',
    verificationFailed: 'Не удалось проверить транзакцию. Повторите попытку.', receiptUnavailable: 'Квитанция ещё готовится. Проверка будет повторена автоматически.', payWithWallet: 'Оплатить кошельком', preparingPayment: 'Подготовка платежа...', openingWallet: 'Открываем кошелёк...', walletPaymentFailed: 'Не удалось выполнить оплату через кошелёк. Повторите попытку.', walletTokenAccountMissing: 'В вашем кошельке отсутствует необходимый токеновый аккаунт.', paymentConfirmed: 'Платёж подтверждён платёжным сервисом.', paymentCompleted: 'Платёж достиг окончательного статуса завершён.', paymentUnderpaid: 'Обнаружен платёж меньше требуемой суммы.', paymentOverpaid: 'Обнаружен платёж больше требуемой суммы.', paymentAmbiguous: 'Найдено несколько совместимых наблюдений; требуется дополнительное разрешение.',
    intentLookupTitle: 'Проверка запроса на оплату', intentLookupDescription: 'Введите идентификатор запроса на оплату, чтобы загрузить и проверить официальные данные платежа.', intentLookupLabel: 'ID запроса на оплату', intentLookupPlaceholder: 'Введите уникальный идентификатор запроса на оплату', checkIntent: 'Проверить запрос', invalidIntentId: 'Недопустимый идентификатор запроса на оплату.'

} as const;

export type CheckoutLabelKey = keyof typeof labels['fa-IR'];
export const checkoutLabelKeys = Object.keys(labels['fa-IR']) as CheckoutLabelKey[];

export function checkoutLabel(locale: PayLocale, key: CheckoutLabelKey): string {
  return (labels[locale] as Record<CheckoutLabelKey, string>)[key] ?? '';
}
