import type { PayLocale } from './types';

const labels = {
  'fa-IR': {
    merchant: 'مرچنت', amount: 'مبلغ', customerTotal: 'مبلغ نهایی مشتری', merchantSettlement: 'دریافتی مرچنت', fee: 'کارمزد درگاه', feePayer: 'پرداخت‌کننده کارمزد', customer: 'مشتری', asset: 'دارایی', network: 'شبکه', destination: 'مقصد', reference: 'مرجع', intentStatus: 'وضعیت پرداخت', commitment: 'تعهد تأیید',
    loadFailed: 'دریافت درخواست پرداخت از سرویس پرداخت ناموفق بود.', expired: 'این درخواست پرداخت منقضی شده است.',
    payInstructions: 'کیف پول را متصل و پرداخت را تأیید کنید. پس از امضا و ارسال تراکنش، سرویس پرداخت SolMint آن را به‌صورت خودکار بررسی می‌کند.',
    walletConnect: 'اتصال کیف پول', walletGeneric: 'کیف پول', walletConnected: 'کیف پول متصل است', walletRequired: 'برای پرداخت، ابتدا کیف پول را متصل کنید.', walletConnectionFailed: 'اتصال کیف پول انجام نشد. دوباره تلاش کنید.', walletSignatureMissing: 'کیف پول امضای تراکنش را برنگرداند. دوباره تلاش کنید.',
    copy: 'کپی', copied: 'کپی شد', connect: 'اتصال', changeWallet: 'تغییر کیف پول', disconnect: 'قطع اتصال', chooseWallet: 'انتخاب کیف پول', walletOptionsHint: 'یکی از کیف پول‌های شناسایی‌شده را انتخاب کنید.', technicalDetails: 'جزئیات فنی پرداخت', checkoutSnapshotDescription: 'جزئیات زیر از Payment Intent دریافت شده‌اند و برای بررسی و تطبیق نمایش داده می‌شوند.',
    signatureLabel: 'امضای تراکنش', signaturePlaceholder: 'امضای تراکنش را وارد کنید', verifyPayment: 'بررسی پرداخت', verifying: 'در حال بررسی پرداخت...',
    verificationSubmitted: 'درخواست بررسی ثبت شد. تا اعلام وضعیت معتبر سرور، پرداخت موفق محسوب نمی‌شود.',
    notDetected: 'این امضای تراکنش هنوز با مرجع این پرداخت در بازه بررسی پیدا نشده است.',
    paymentConfirmed: 'پرداخت توسط سرویس پرداخت تأیید شد.', paymentCompleted: 'پرداخت با وضعیت نهایی تکمیل شد.', paymentUnderpaid: 'پرداخت کمتر از مبلغ موردنیاز شناسایی شد.', paymentOverpaid: 'پرداخت بیشتر از مبلغ موردنیاز شناسایی شد.', paymentAmbiguous: 'چند مشاهده سازگار شناسایی شد و بررسی نیاز به اقدام بعدی دارد.',
    verificationFailed: 'بررسی تراکنش کامل نشد. دوباره تلاش کنید.', receiptUnavailable: 'رسید در حال آماده‌سازی است. دوباره بررسی می‌شود.', payWithWallet: 'پرداخت با کیف پول', preparingPayment: 'در حال آماده‌سازی پرداخت...', openingWallet: 'در حال باز کردن کیف پول...', walletPaymentFailed: 'پرداخت با کیف پول انجام نشد. دوباره تلاش کنید.', walletTokenAccountMissing: 'کیف پول شما حساب توکن لازم را ندارد.', manualVerification: 'بررسی با امضای تراکنش', manualVerificationHint: 'فقط در صورت پشتیبانی‌نشدن پرداخت مستقیم توسط کیف پول، امضای تراکنش را وارد و بررسی کنید.', intentLookupTitle: 'بررسی درخواست پرداخت', intentLookupDescription: 'شناسه درخواست پرداخت را وارد کنید تا تصویر رسمی پرداخت دریافت و بررسی شود.', intentLookupLabel: 'شناسه درخواست پرداخت', intentLookupPlaceholder: 'شناسه یکتای درخواست پرداخت را وارد کنید', checkIntent: 'بررسی Intent', invalidIntentId: 'شناسه درخواست پرداخت نامعتبر است.'
  },
  'en-US': {
    merchant: 'Merchant', amount: 'Amount', customerTotal: 'Customer total', merchantSettlement: 'Merchant receives', fee: 'Gateway fee', feePayer: 'Fee payer', customer: 'Customer', asset: 'Asset', network: 'Network', destination: 'Destination', reference: 'المرجع', intentStatus: 'Intent status', commitment: 'Verification commitment',
    loadFailed: 'The Payment Intent could not be retrieved from the payment service.', expired: 'This Payment Intent has expired.',
    payInstructions: 'Connect your wallet and approve the payment. After signing and sending, SolMint Pay verifies the resulting transaction automatically.',
    walletConnect: 'Wallet connection', walletGeneric: 'Wallet', walletConnected: 'Wallet connected', walletRequired: 'Connect a wallet before paying.', walletConnectionFailed: 'Wallet connection failed. Try again.', walletSignatureMissing: 'The wallet did not return a transaction signature. Try again.',
    copy: 'Copy', copied: 'Copied', connect: 'Connect', changeWallet: 'Change wallet', disconnect: 'Disconnect', chooseWallet: 'Choose a wallet', walletOptionsHint: 'Select one of the detected wallets.', technicalDetails: 'Payment details', checkoutSnapshotDescription: 'These values come from the Payment Intent and are shown for inspection and reconciliation.',
    signatureLabel: 'توقيع المعاملة', signaturePlaceholder: 'Enter the transaction signature', verifyPayment: 'Verify payment', verifying: 'Verifying payment...',
    verificationSubmitted: 'Verification was requested. The payment is not considered successful until the server reports an authoritative state.',
    notDetected: 'This signature was not found for this Payment Intent reference and verification window.',
    paymentConfirmed: 'The payment was confirmed by the payment service.', paymentCompleted: 'The payment reached the final completed state.', paymentUnderpaid: 'A payment below the required amount was detected.', paymentOverpaid: 'A payment above the required amount was detected.', paymentAmbiguous: 'Multiple compatible observations were found and the payment requires further resolution.',
    verificationFailed: 'The transaction could not be verified. Try again.', receiptUnavailable: 'The receipt is still being prepared. We will check again.', payWithWallet: 'Pay with wallet', preparingPayment: 'Preparing payment...', openingWallet: 'Opening wallet...', walletPaymentFailed: 'Wallet payment could not be completed. Try again.', walletTokenAccountMissing: 'Your wallet does not have the required token account.', manualVerification: 'Verify with signature', manualVerificationHint: 'Use this only when your wallet does not support direct checkout; enter the transaction signature for verification.', intentLookupTitle: 'Check Payment Intent', intentLookupDescription: 'Enter a Payment Intent ID to load and inspect the authoritative payment snapshot.', intentLookupLabel: 'Payment Intent ID', intentLookupPlaceholder: 'Enter the Payment Intent UUID', checkIntent: 'Check Intent', invalidIntentId: 'The Payment Intent ID is invalid.'
  },
  ar: {
    merchant: 'التاجر', amount: 'المبلغ', customerTotal: 'إجمالي العميل', merchantSettlement: 'ما يستلمه التاجر', fee: 'رسوم البوابة', feePayer: 'دافع الرسوم', customer: 'العميل', asset: 'الأصل', network: 'الشبكة', destination: 'الوجهة', reference: 'المرجع', intentStatus: 'حالة الدفع', commitment: 'التزام التحقق',
    loadFailed: 'تعذر جلب طلب الدفع من خدمة الدفع.', expired: 'انتهت صلاحية طلب الدفع هذا.',
    payInstructions: 'صِل محفظتك وأكّد الدفع. بعد التوقيع والإرسال، تقوم خدمة SolMint Pay بالتحقق من المعاملة تلقائياً.',
    walletConnect: 'اتصال المحفظة', walletGeneric: 'المحفظة', walletConnected: 'المحفظة متصلة', walletRequired: 'يجب توصيل محفظة قبل الدفع.', walletConnectionFailed: 'تعذر اتصال المحفظة. حاول مرة أخرى.', walletSignatureMissing: 'لم تُعد المحفظة توقيع المعاملة. حاول مرة أخرى.',
    copy: 'نسخ', copied: 'تم النسخ', connect: 'اتصال', changeWallet: 'تغيير المحفظة', disconnect: 'قطع الاتصال', chooseWallet: 'اختيار المحفظة', walletOptionsHint: 'اختر إحدى المحافظ التي تم اكتشافها.', technicalDetails: 'تفاصيل الدفع', checkoutSnapshotDescription: 'تأتي هذه القيم من Payment Intent وتُعرض للفحص والمطابقة.',
    signatureLabel: 'Подпись транзакции', signaturePlaceholder: 'أدخل توقيع المعاملة', verifyPayment: 'تحقق من الدفع', verifying: 'جارٍ التحقق من الدفع...',
    verificationSubmitted: 'تم طلب التحقق. لن يعتبر الدفع ناجحاً حتى يعلن الخادم حالة موثوقة.',
    notDetected: 'لم يتم العثور على هذا التوقيع ضمن مرجع الدفع ونافذة التحقق.',
    paymentConfirmed: 'تم تأكيد الدفع بواسطة خدمة الدفع.', paymentCompleted: 'اكتملت عملية الدفع بحالة نهائية.', paymentUnderpaid: 'تم اكتشاف دفع أقل من المبلغ المطلوب.', paymentOverpaid: 'تم اكتشاف دفع أكبر من المبلغ المطلوب.', paymentAmbiguous: 'تم العثور على ملاحظات متوافقة متعددة ويحتاج الدفع إلى معالجة إضافية.',
    verificationFailed: 'تعذر التحقق من المعاملة. حاول مرة أخرى.', receiptUnavailable: 'يتم تجهيز الإيصال. ستتم إعادة المحاولة تلقائياً.', payWithWallet: 'الدفع بالمحفظة', preparingPayment: 'جارٍ تجهيز الدفع...', openingWallet: 'جارٍ فتح المحفظة...', walletPaymentFailed: 'تعذر إكمال الدفع بالمحفظة. حاول مرة أخرى.', walletTokenAccountMissing: 'لا تحتوي محفظتك على حساب الرمز المطلوب.', manualVerification: 'التحقق بتوقيع المعاملة', manualVerificationHint: 'استخدم هذه الطريقة فقط إذا كانت محفظتك لا تدعم الدفع المباشر؛ أدخل توقيع المعاملة للتحقق.', intentLookupTitle: 'التحقق من طلب الدفع', intentLookupDescription: 'أدخل معرّف طلب الدفع لتحميل البيانات الرسمية للدفع وفحصها.', intentLookupLabel: 'معرّف طلب الدفع', intentLookupPlaceholder: 'أدخل المعرّف الفريد لطلب الدفع', checkIntent: 'تحقق من Intent', invalidIntentId: 'معرّف طلب الدفع غير صالح.'
  },
  ru: {
    merchant: 'Мерчант', amount: 'Сумма', customerTotal: 'Итого клиента', merchantSettlement: 'Получит мерчант', fee: 'Комиссия шлюза', feePayer: 'Плательщик комиссии', customer: 'Клиент', asset: 'Актив', network: 'Сеть', destination: 'Получатель', reference: 'Reference', intentStatus: 'Статус платежа', commitment: 'Требование проверки',
    loadFailed: 'Не удалось получить запрос на оплату из платёжного сервиса.', expired: 'Срок действия этого запроса на оплату истёк.',
    payInstructions: 'Подключите кошелёк и подтвердите оплату. После подписи и отправки платёжный сервис SolMint Pay автоматически проверит транзакцию.',
    walletConnect: 'Подключение кошелька', walletGeneric: 'Кошелёк', walletConnected: 'Кошелёк подключён', walletRequired: 'Перед оплатой подключите кошелёк.', walletConnectionFailed: 'Не удалось подключить кошелёк. Повторите попытку.', walletSignatureMissing: 'Кошелёк не вернул подпись транзакции. Повторите попытку.',
    copy: 'Копировать', copied: 'Скопировано', connect: 'Подключить', changeWallet: 'Сменить кошелёк', disconnect: 'Отключить', chooseWallet: 'Выберите кошелёк', walletOptionsHint: 'Выберите один из обнаруженных кошельков.', technicalDetails: 'Детали платежа', checkoutSnapshotDescription: 'Эти значения получены из запроса на оплату и показаны для проверки и сверки.',
    signatureLabel: 'Transaction Signature', signaturePlaceholder: 'Введите подпись транзакции', verifyPayment: 'Проверить оплату', verifying: 'Проверка оплаты...',
    verificationSubmitted: 'Проверка запрошена. Оплата не считается успешной, пока сервер не сообщит авторитетный статус.',
    notDetected: 'Эта подпись не найдена для указанного платежа в окне проверки.',
    paymentConfirmed: 'Платёж подтверждён платёжным сервисом.', paymentCompleted: 'Платёж достиг окончательного статуса завершён.', paymentUnderpaid: 'Обнаружен платёж меньше требуемой суммы.', paymentOverpaid: 'Обнаружен платёж больше требуемой суммы.', paymentAmbiguous: 'Найдено несколько совместимых наблюдений; требуется дополнительное разрешение.',
    verificationFailed: 'Не удалось проверить транзакцию. Повторите попытку.', receiptUnavailable: 'Квитанция ещё готовится. Проверка будет повторена автоматически.', payWithWallet: 'Оплатить кошельком', preparingPayment: 'Подготовка платежа...', openingWallet: 'Открываем кошелёк...', walletPaymentFailed: 'Не удалось выполнить оплату через кошелёк. Повторите попытку.', walletTokenAccountMissing: 'В вашем кошельке отсутствует необходимый токеновый аккаунт.', manualVerification: 'Проверка по подписи', manualVerificationHint: 'Используйте этот способ только если кошелёк не поддерживает прямую оплату; введите подпись транзакции для проверки.', intentLookupTitle: 'Проверка запроса на оплату', intentLookupDescription: 'Введите идентификатор запроса на оплату, чтобы загрузить и проверить официальные данные платежа.', intentLookupLabel: 'ID запроса на оплату', intentLookupPlaceholder: 'Введите уникальный идентификатор запроса на оплату', checkIntent: 'Проверить Intent', invalidIntentId: 'Недопустимый ID запроса на оплату.'
  },
} as const;

export type CheckoutLabelKey = keyof typeof labels['fa-IR'];
export const checkoutLabelKeys = Object.keys(labels['fa-IR']) as CheckoutLabelKey[];

export function checkoutLabel(locale: PayLocale, key: CheckoutLabelKey): string {
  return (labels[locale] as Record<CheckoutLabelKey, string>)[key] ?? '';
}
