-- Historical production migration ledger entry.
--
-- This migration was already applied to SolMint Pay Production before it was
-- retained in the repository. The original SQL body is not recoverable from
-- the current repository history. This no-op placeholder preserves the exact
-- applied version so Supabase CLI can reconcile the historical migration chain
-- without replaying or inventing a data mutation.
--
-- Do not add new production schema/data changes to this file. Create a new
-- uniquely timestamped migration instead.
